"""Spec 148 Slice 1 — `/agency` slash family.

The plugin manifest exposes exactly one slash command (`/help`). Spec 029
ships `agency_welcome` / `intent_bootstrap` as MCP tools, but a human in
Claude Code has no one-keystroke entry. Per the plugin-development skill,
a plugin's slash commands ARE its conversational surface.

Slice 1 ships TWO static commands generated by `install.generate()` from
the live registry:
- `commands/agency.md` — `/agency [query]` routes to tiered discovery
  (`mcp__agency__search`) when given a query, else `agency_welcome`.
- `commands/agency-onboard.md` — `/agency-onboard` runs the describe →
  configure → confirm → capture interview (static prompt-list form in
  Slice 1; the Spec 147 AnthropicDriver-powered conversational version
  is Slice 2).

Both are valid Agent-Skill command frontmatter (description first line).

Slice 2+ — per-skill `/agency-<skill>` shortcuts (derived rank, Open-Q 4),
SessionStart hook offer, Anthropic-driven interview, provenance round-trip.
"""
from __future__ import annotations

import re

import pytest

from agency.engine import Engine
from agency import install


@pytest.fixture
def files():
    e = Engine(":memory:")
    try:
        return install.generate(e)
    finally:
        e.memory.close()


# ── the two new command files are generated ────────────────────────────────
def test_generate_emits_agency_command(files):
    assert "commands/agency.md" in files, (
        "Spec 148 Slice 1: install.generate must emit the /agency dispatcher")


def test_generate_emits_agency_onboard_command(files):
    assert "commands/agency-onboard.md" in files, (
        "Spec 148 Slice 1: install.generate must emit the /agency-onboard "
        "interview command")


def test_help_command_still_emitted(files):
    """Slice 1 ADDS commands; it must not drop the existing /help."""
    assert "commands/help.md" in files


# ── frontmatter shape (per developing-claude-code-plugins skill) ───────────
def _frontmatter(md: str) -> str:
    """Return the YAML frontmatter block (between the first two `---`)."""
    assert md.startswith("---\n"), "command file must open with YAML frontmatter"
    end = md.find("\n---\n", 4)
    assert end != -1, "command frontmatter must be terminated with ---"
    return md[4:end]


def test_agency_command_has_description_frontmatter(files):
    fm = _frontmatter(files["commands/agency.md"])
    assert "description:" in fm, "command needs a `description:` frontmatter key"


def test_agency_onboard_command_has_description_frontmatter(files):
    fm = _frontmatter(files["commands/agency-onboard.md"])
    assert "description:" in fm


# ── body content: the dispatcher routes to discovery + welcome ─────────────
def test_agency_command_body_references_search_and_welcome(files):
    body = files["commands/agency.md"]
    # The dispatcher names both routes — tiered discovery + the welcome.
    assert "search" in body, "/agency [query] must route to search (tiered discovery)"
    assert "agency_welcome" in body, "/agency (no query) must print agency_welcome"


def test_agency_onboard_body_names_the_four_beats(files):
    body = files["commands/agency-onboard.md"].lower()
    # describe → configure → confirm → capture (the four-beat interview).
    for beat in ("describe", "configure", "confirm", "capture"):
        assert beat in body, f"/agency-onboard body must name the '{beat}' beat"


def test_agency_onboard_body_names_intent_bootstrap(files):
    """The final beat derives intent_bootstrap fields from captured turns."""
    body = files["commands/agency-onboard.md"]
    assert "intent_bootstrap" in body


# ── derivation invariant: commands derive from the live registry ───────────
def test_command_set_includes_documented_core(files):
    """Per CLAUDE.md rule 8 — a SUBSET invariant on the command surface:
    the documented core commands MUST exist; future commands may extend."""
    command_files = {k for k in files if k.startswith("commands/")}
    documented_core = {"commands/help.md", "commands/agency.md",
                       "commands/agency-onboard.md"}
    missing = documented_core - command_files
    assert not missing, f"install dropped documented core commands: {missing}"


def test_generated_commands_are_nonempty(files):
    for path in ("commands/agency.md", "commands/agency-onboard.md"):
        assert files[path].strip(), f"{path} must not be empty"
