"""Spec 020 v2 — dogfood.import JSON replay.

The matching reverse of dogfood.export (Spec 020 line 69-73): read a
portable JSON file and replay it into a (typically fresh) DB so a
conflicted DB can be regenerated by replaying both branches' JSON
exports.

Round-trip discipline: a graph exported, wiped, and re-imported must
contain every original node (same id, same properties, same vfrom/vto
window) and every original edge. Closes the merge-conflict recovery
loop.
"""
import json
import tempfile

import pytest

from agency.engine import Engine


@pytest.fixture
def engine():
    return Engine(tempfile.mktemp(suffix=".db"))


@pytest.fixture
def iid(engine):
    return engine.intent.capture_and_confirm(
        "test dogfood.import", "json replay", "x", owner="user")


def _call(engine, iid, verb, **kw):
    r, _ = engine.registry.invoke(
        engine.memory, iid, "dogfood", verb,
        agent_id="agent:test", **kw)
    return r


# ---------------------------------------------------------------------------
# Verb registration + payload shape.
# ---------------------------------------------------------------------------


def test_import_verb_registered(engine):
    cap = engine.registry.get("dogfood")
    assert "import" in cap.verbs


def test_import_returns_counts_and_version(engine, iid, tmp_path):
    target = tmp_path / "x.json"
    _call(engine, iid, "export", path=str(target))
    fresh = Engine(tempfile.mktemp(suffix=".db"))
    fresh_iid = fresh.intent.capture_and_confirm("r", "x", "x", owner="user")
    r, _ = fresh.registry.invoke(
        fresh.memory, fresh_iid, "dogfood", "import",
        agent_id="agent:test", path=str(target))
    assert "imported_nodes" in r and isinstance(r["imported_nodes"], int)
    assert "imported_edges" in r and isinstance(r["imported_edges"], int)
    assert r["version"] == 1
    assert r["imported_nodes"] >= 1   # the source's bootstrap intent


def test_import_rejects_unknown_version(engine, iid, tmp_path):
    target = tmp_path / "x.json"
    payload = {"version": 999, "generated_at": 0, "nodes": [], "edges": []}
    target.write_text(json.dumps(payload))
    with pytest.raises(ValueError, match="version"):
        _call(engine, iid, "import", path=str(target))


def test_import_missing_file_raises(engine, iid, tmp_path):
    target = tmp_path / "does-not-exist.json"
    with pytest.raises(FileNotFoundError):
        _call(engine, iid, "import", path=str(target))


# ---------------------------------------------------------------------------
# Preservation: ids, properties, bi-temporal windows.
# ---------------------------------------------------------------------------


def test_import_preserves_node_ids(engine, iid, tmp_path):
    _call(engine, iid, "note",
          observation="round-trip text", plan_slug="020-rt")
    target = tmp_path / "x.json"
    _call(engine, iid, "export", path=str(target))
    src_payload = json.loads(target.read_text())
    src_ids = {n["id"] for n in src_payload["nodes"]}

    fresh = Engine(tempfile.mktemp(suffix=".db"))
    fresh_iid = fresh.intent.capture_and_confirm(
        "fresh", "x", "x", owner="user")
    fresh.registry.invoke(
        fresh.memory, fresh_iid, "dogfood", "import",
        agent_id="agent:test", path=str(target))

    after_rows = fresh.memory.g.query("MATCH (n) RETURN n")
    after_ids = {r["n"].get("properties", {}).get("id") for r in after_rows}
    # every original id appears in the fresh DB
    missing = src_ids - after_ids
    assert not missing, f"missing imported ids: {missing}"


def test_import_preserves_reflection_properties(engine, iid, tmp_path):
    _call(engine, iid, "note",
          observation="preserve me", plan_slug="020-prop")
    target = tmp_path / "x.json"
    _call(engine, iid, "export", path=str(target))

    fresh = Engine(tempfile.mktemp(suffix=".db"))
    fresh_iid = fresh.intent.capture_and_confirm(
        "fresh", "x", "x", owner="user")
    fresh.registry.invoke(
        fresh.memory, fresh_iid, "dogfood", "import",
        agent_id="agent:test", path=str(target))

    reflections = fresh.memory.find("Reflection")
    matched = [r for r in reflections if r.get("text") == "preserve me"]
    assert matched, "imported Reflection should be findable by property"
    assert matched[0].get("plan_slug") == "020-prop"


def test_import_preserves_vfrom_vto_window(engine, iid, tmp_path):
    _call(engine, iid, "note",
          observation="windowed", plan_slug="020-win")
    target = tmp_path / "x.json"
    _call(engine, iid, "export", path=str(target))
    src = json.loads(target.read_text())
    src_node = next(n for n in src["nodes"]
                    if n.get("label") == "Reflection"
                    and n["properties"].get("text") == "windowed")
    src_vfrom = src_node["properties"]["vfrom"]
    src_vto = src_node["properties"]["vto"]

    fresh = Engine(tempfile.mktemp(suffix=".db"))
    fresh_iid = fresh.intent.capture_and_confirm(
        "fresh", "x", "x", owner="user")
    fresh.registry.invoke(
        fresh.memory, fresh_iid, "dogfood", "import",
        agent_id="agent:test", path=str(target))
    after = fresh.memory.recall(src_node["id"])
    assert after is not None
    assert after["vfrom"] == src_vfrom
    assert after["vto"] == src_vto


def test_import_recreates_edges(engine, iid, tmp_path):
    _call(engine, iid, "note",
          observation="edges", plan_slug="020-edge")
    target = tmp_path / "x.json"
    _call(engine, iid, "export", path=str(target))

    fresh = Engine(tempfile.mktemp(suffix=".db"))
    fresh_iid = fresh.intent.capture_and_confirm(
        "fresh", "x", "x", owner="user")
    fresh.registry.invoke(
        fresh.memory, fresh_iid, "dogfood", "import",
        agent_id="agent:test", path=str(target))

    erows = fresh.memory.g.query("MATCH (a)-[e]->(b) RETURN a, e, b")

    def _edge_type(r):
        e = r["e"]
        return (e.get("type") or e.get("rel_type")
                or e.get("relationship") or "")

    types = {_edge_type(r) for r in erows}
    # dogfood.note links SERVES + OBSERVED_DURING
    assert "SERVES" in types or "OBSERVED_DURING" in types


# ---------------------------------------------------------------------------
# Round-trip: export → fresh DB → import → re-export → identical node set.
# ---------------------------------------------------------------------------


def test_round_trip_export_import_reexport(engine, iid, tmp_path):
    """Closing Spec 020's merge-conflict recovery loop. Export, replay
    against a fresh DB, re-export — the imported node ids must be a
    subset of the re-exported node ids (the fresh DB will add its own
    bootstrap + import-Invocation nodes; the original ones MUST persist).
    """
    _call(engine, iid, "note", observation="rt-1", plan_slug="rt")
    _call(engine, iid, "note", observation="rt-2", plan_slug="rt")
    first = tmp_path / "first.json"
    _call(engine, iid, "export", path=str(first))
    src_ids = {n["id"] for n in json.loads(first.read_text())["nodes"]}

    fresh = Engine(tempfile.mktemp(suffix=".db"))
    fresh_iid = fresh.intent.capture_and_confirm(
        "fresh", "x", "x", owner="user")
    fresh.registry.invoke(
        fresh.memory, fresh_iid, "dogfood", "import",
        agent_id="agent:test", path=str(first))
    second = tmp_path / "second.json"
    fresh.registry.invoke(
        fresh.memory, fresh_iid, "dogfood", "export",
        agent_id="agent:test", path=str(second))
    dst_ids = {n["id"] for n in json.loads(second.read_text())["nodes"]}

    missing = src_ids - dst_ids
    assert not missing, \
        f"round-trip dropped node ids: {missing}"


# ---------------------------------------------------------------------------
# Clock advance: future writes must not collide with imported vfroms.
# ---------------------------------------------------------------------------


def test_import_advances_logical_clock(engine, iid, tmp_path):
    """After import, the memory's _tick must be > max(vfrom, vto) seen in
    the import so subsequent writes don't reuse stale ticks. Without
    this, a new record() call could land at a vfrom that overlaps an
    imported node's window and confuse provenance queries."""
    _call(engine, iid, "note",
          observation="clock-test", plan_slug="020-clk")
    target = tmp_path / "x.json"
    _call(engine, iid, "export", path=str(target))
    src = json.loads(target.read_text())
    max_tick = max(
        n["properties"].get("vfrom", 0)
        for n in src["nodes"]
        if isinstance(n["properties"].get("vfrom"), int)
    )

    fresh = Engine(tempfile.mktemp(suffix=".db"))
    fresh_iid = fresh.intent.capture_and_confirm(
        "fresh", "x", "x", owner="user")
    fresh.registry.invoke(
        fresh.memory, fresh_iid, "dogfood", "import",
        agent_id="agent:test", path=str(target))
    # After import, the next _now() tick must exceed the max imported.
    next_tick = fresh.memory._now()
    assert next_tick > max_tick
