"""Spec 020 finish — dogfood.export JSON dump.

The merge-conflict recovery fallback (Spec 020 line 69-73): dump the
bi-temporal graph to a portable JSON file so a conflicted DB can be
regenerated by replaying both branches' JSON exports.

Tests:
  - export of empty graph produces well-formed JSON shape
  - export captures Reflection nodes + properties
  - export captures Intent nodes with the Spec 048 owner + parent_intent_id
  - export captures graph edges (SERVES, OBSERVED_DURING, PARENT_INTENT)
  - export writes to the given path; returns {path, nodes, edges, bytes}
  - export defaults to .agency/export-<ts>.json when no path given
  - export is pure (transform) — no graph writes
"""
import json
import os
import tempfile

import pytest

from agency.engine import Engine


@pytest.fixture
def engine():
    return Engine(tempfile.mktemp(suffix=".db"))


@pytest.fixture
def iid(engine):
    return engine.intent.capture_and_confirm(
        "test dogfood.export", "json dump", "x", owner="user")


def _call(engine, iid, verb, **kw):
    r, _ = engine.registry.invoke(
        engine.memory, iid, "dogfood", verb,
        agent_id="agent:test", **kw)
    return r


# ---------------------------------------------------------------------------
# Verb registration + payload shape.
# ---------------------------------------------------------------------------


def test_export_verb_registered(engine):
    cap = engine.registry.get("dogfood")
    assert "export" in cap.verbs


def test_export_returns_payload_with_path_and_counts(engine, iid, tmp_path):
    target = tmp_path / "export.json"
    r = _call(engine, iid, "export", path=str(target))
    assert "path" in r and r["path"] == str(target)
    assert "nodes" in r and isinstance(r["nodes"], int)
    assert "edges" in r and isinstance(r["edges"], int)
    assert "bytes" in r and isinstance(r["bytes"], int)


def test_export_writes_well_formed_json(engine, iid, tmp_path):
    target = tmp_path / "x.json"
    _call(engine, iid, "export", path=str(target))
    assert target.exists()
    data = json.loads(target.read_text())
    # Top-level keys per Spec 020 §"export shape" (panel addition).
    assert "version" in data
    assert "nodes" in data and isinstance(data["nodes"], list)
    assert "edges" in data and isinstance(data["edges"], list)


# ---------------------------------------------------------------------------
# Node capture: Reflections + Intents.
# ---------------------------------------------------------------------------


def test_export_captures_reflection_nodes(engine, iid, tmp_path):
    _call(engine, iid, "note",
          observation="export test obs", plan_slug="020-central-graph-db")
    target = tmp_path / "x.json"
    r = _call(engine, iid, "export", path=str(target))
    assert r["nodes"] >= 2   # at least the Intent + the Reflection
    data = json.loads(target.read_text())
    reflections = [n for n in data["nodes"] if n.get("label") == "Reflection"]
    assert reflections
    me = reflections[0]
    assert "id" in me and "properties" in me
    assert me["properties"].get("text") == "export test obs"
    assert me["properties"].get("plan_slug") == "020-central-graph-db"


def test_export_captures_intent_with_owner_and_parent(engine, iid, tmp_path):
    """Spec 048 extension: Intent's owner + parent_intent_id round-trip
    through the JSON export."""
    child = engine.intent.capture_and_confirm(
        "child", "x", "x", parent_intent_id=iid)
    target = tmp_path / "x.json"
    _call(engine, iid, "export", path=str(target))
    data = json.loads(target.read_text())
    intents = [n for n in data["nodes"] if n.get("label") == "Intent"]
    parent = next(i for i in intents if i["id"] == iid)
    me = next(i for i in intents if i["id"] == child)
    assert parent["properties"]["owner"] == "user"
    assert me["properties"]["owner"] == "agent"
    assert me["properties"]["parent_intent_id"] == iid


# ---------------------------------------------------------------------------
# Edge capture.
# ---------------------------------------------------------------------------


def test_export_captures_edges(engine, iid, tmp_path):
    _call(engine, iid, "note",
          observation="x", plan_slug="020")
    target = tmp_path / "x.json"
    r = _call(engine, iid, "export", path=str(target))
    assert r["edges"] >= 1
    data = json.loads(target.read_text())
    edges = data["edges"]
    edge_types = {e.get("type") for e in edges}
    # dogfood.note links OBSERVED_DURING + SERVES.
    assert "OBSERVED_DURING" in edge_types or "SERVES" in edge_types


# ---------------------------------------------------------------------------
# Defaults + purity.
# ---------------------------------------------------------------------------


def test_export_default_path_under_dot_agency(engine, iid, tmp_path,
                                                monkeypatch):
    """When path is empty, export defaults to .agency/export-<ts>.json
    under the current working directory."""
    monkeypatch.chdir(tmp_path)
    agency_dir = tmp_path / ".agency"
    agency_dir.mkdir()
    r = _call(engine, iid, "export", path="")
    assert r["path"].startswith(str(agency_dir))
    assert r["path"].endswith(".json")
    assert os.path.isfile(r["path"])


def test_export_is_pure_no_graph_writes(engine, iid, tmp_path):
    """Export is a transform — calling it must not change the node count."""
    _call(engine, iid, "note", observation="x", plan_slug="x")
    before_nodes = len(list(engine.memory.find("Reflection")))
    before_intents = len(list(engine.memory.find("Intent")))
    _call(engine, iid, "export", path=str(tmp_path / "x.json"))
    after_nodes = len(list(engine.memory.find("Reflection")))
    after_intents = len(list(engine.memory.find("Intent")))
    assert before_nodes == after_nodes
    assert before_intents == after_intents


def test_export_default_path_uses_ns_to_avoid_collision(engine, iid, tmp_path,
                                                         monkeypatch):
    """sc:sc-analyze F6 review: two exports in quick succession must
    not clobber each other (review found time.time() would collide;
    fix uses time.time_ns)."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / ".agency").mkdir()
    r1 = _call(engine, iid, "export", path="")
    r2 = _call(engine, iid, "export", path="")
    assert r1["path"] != r2["path"], \
        "default paths must differ even when called back-to-back"
    assert os.path.isfile(r1["path"])
    assert os.path.isfile(r2["path"])


def test_export_empty_graph_returns_valid_json(tmp_path):
    """An engine with only the bootstrap Intent should export to valid
    JSON with at least version + nodes + edges keys (empty lists ok)."""
    e = Engine(tempfile.mktemp(suffix=".db"))
    i = e.intent.capture_and_confirm("empty", "x", "x", owner="user")
    r, _ = e.registry.invoke(
        e.memory, i, "dogfood", "export",
        agent_id="agent:test", path=str(tmp_path / "empty.json"))
    data = json.loads((tmp_path / "empty.json").read_text())
    assert data["version"] >= 1
    assert isinstance(data["nodes"], list)
    assert isinstance(data["edges"], list)
    # Should contain the bootstrap Intent at minimum.
    intents = [n for n in data["nodes"] if n.get("label") == "Intent"]
    assert any(n["id"] == i for n in intents)
