"""Unified ``.agency/config.yaml`` — Spec 328 Slice 1 (resolver + registry).

A single home for all agency config. A key resolves **env var → config.yaml →
built-in default** (the same precedence shape as ``_db_path.resolve_db_path``).
Capabilities ``register_config_section`` their own keys, so the live set is the
union of all registered config — no frozen audit (Goal 4). ``config_set``
persists a value to the file.

Slice 1 is the resolver/registry/precedence. The annotated, comment-preserving
scaffold generator + doctor validation are later slices.
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Any

try:  # frugal: yaml is a core dep (Spec 328); guard so import never hard-crashes.
    import yaml
except ImportError:  # pragma: no cover - yaml is a declared dependency
    yaml = None


@dataclass(frozen=True)
class ConfigKey:
    """One config knob: its name, env-var alias, default, doc, and optional enum.
    ``secret`` keys are env-only — the scaffold writes a ``${env:VAR}`` reference,
    never the literal value (doctor reports presence)."""
    name: str
    env: str = ""
    default: Any = None
    doc: str = ""
    enum: tuple | None = None
    secret: bool = False


_REGISTRY: dict[str, list[ConfigKey]] = {}


def register_config_section(name: str, keys: list[ConfigKey]) -> None:
    """Register (or replace) a config section. Core + each capability call this."""
    _REGISTRY[name] = list(keys)


def registered_keys() -> list[str]:
    """Every registered key as ``section.name`` — the union = 'all agency config'."""
    return [f"{section}.{k.name}" for section, keys in _REGISTRY.items() for k in keys]


def secret_keys() -> list[str]:
    """Every registered secret key as ``section.name`` (env-only — never written
    literal). Computed live from the registry, not a frozen list (Goal 4)."""
    return [f"{section}.{k.name}"
            for section, keys in _REGISTRY.items() for k in keys if k.secret]


def _lookup(dotted: str) -> tuple[str, ConfigKey] | None:
    section, _, name = dotted.partition(".")
    for k in _REGISTRY.get(section, []):
        if k.name == name:
            return section, k
    return None


def _resolve_config_path() -> str:
    """``AGENCY_CONFIG`` env → ``$CWD/.agency/config.yaml`` (mirrors _db_path)."""
    return os.environ.get("AGENCY_CONFIG") or os.path.join(
        os.getcwd(), ".agency", "config.yaml")


def _read(path: str) -> dict:
    if not path or yaml is None or not os.path.exists(path):
        return {}
    try:
        with open(path, encoding="utf-8") as f:
            data = yaml.safe_load(f)
        return data if isinstance(data, dict) else {}
    except (OSError, yaml.YAMLError):  # corrupt/unreadable → fall through to defaults
        return {}


def config_resolve(dotted: str, *, path: str | None = None) -> dict:
    """Resolve a registered key to ``{"value", "source"}`` where source is one of
    ``env`` / ``file`` / ``default`` (so doctor can explain *why* a value is what
    it is). Raises ``KeyError`` for an unregistered key."""
    found = _lookup(dotted)
    if found is None:
        raise KeyError(f"unregistered config key: {dotted!r}")
    section, key = found
    if key.env and os.environ.get(key.env) is not None:
        return {"value": os.environ[key.env], "source": "env"}
    data = _read(path or _resolve_config_path())
    sec = data.get(section)
    if isinstance(sec, dict) and key.name in sec:
        return {"value": sec[key.name], "source": "file"}
    return {"value": key.default, "source": "default"}


def config_get(dotted: str, *, path: str | None = None) -> Any:
    """The resolved value (env > file > default)."""
    return config_resolve(dotted, path=path)["value"]


def config_set(dotted: str, value: Any, *, path: str | None = None) -> None:
    """Persist ``value`` for ``dotted`` to the config file (durable across
    processes). Slice 2 adds comment-preserving round-trip + scaffold rendering."""
    if yaml is None:  # pragma: no cover - yaml is a declared dependency
        raise RuntimeError("PyYAML is required for config_set")
    section, _, name = dotted.partition(".")
    target = path or _resolve_config_path()
    data = _read(target)
    data.setdefault(section, {})[name] = value
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as f:
        yaml.safe_dump(data, f, default_flow_style=False, sort_keys=False)


# ── Spec 328 Slice 2 — the annotated scaffold generator ───────────────────────
_HEADER = (
    "# .agency/config.yaml — all agency config (Spec 328). Safe to edit.\n"
    "# Precedence: environment variable > this file > built-in default.\n"
    "# Generated by setup / `agency install`; re-running repairs missing keys\n"
    "# non-destructively (your edits and comments are preserved).\n"
)


def _yaml_scalar(val: Any) -> str:
    """Render ``val`` as a YAML-safe scalar: bare for simple tokens, JSON-quoted
    (valid YAML) for anything with special chars. Booleans → ``true``/``false``."""
    if isinstance(val, bool):
        return "true" if val else "false"
    if val is None:
        return "null"
    if isinstance(val, (int, float)):
        return str(val)
    s = str(val)
    if s and all(c.isalnum() or c in "_./-" for c in s):
        return s
    import json
    return json.dumps(s)                       # double-quoted → valid YAML scalar


def _render_section(section: str, keys: list[ConfigKey]) -> str:
    """One annotated YAML section: a key per line at its default + a ``#`` comment.
    Secret keys render a ``${env:VAR}`` reference, never the literal value."""
    lines = [f"{section}:"]
    for k in keys:
        value = f"${{env:{k.env or 'UNSET'}}}" if k.secret else k.default
        comment = k.doc
        if k.enum:
            comment = f"{comment} ({'|'.join(map(str, k.enum))})".strip()
        if k.env and not k.secret:
            comment = f"{comment} [env: {k.env}]".strip()
        line = f"  {k.name}: {_yaml_scalar(value)}"
        if comment:
            line += f"  # {comment}"
        lines.append(line)
    return "\n".join(lines) + "\n"


def _ensure_core_sections() -> None:
    """Register the core-discipline sections that live in their own module. The
    ``frugal`` section registers on ``import agency._frugal`` — but the M1 hook
    handlers import it lazily, so a scaffold during ``install``/``setup`` (before
    any hook fires) would otherwise miss it. Capability sections register when the
    engine loads them; this only nudges the core discipline. Best-effort."""
    try:
        from . import _frugal  # noqa: F401 — import side effect registers 'frugal'
    except Exception:
        pass


def config_scaffold(path: str | None = None) -> str:
    """Generate / repair ``.agency/config.yaml`` — every registered section at its
    defaults with per-key comments. Idempotent + **non-destructive**: a present
    section is never rewritten (user edits + comments survive); only **missing**
    sections are appended. Returns the path written.

    # frugal: section-granular merge — a NEW section appears, but a key added to
    # an EXISTING section is not back-filled into the file (config_get still
    # resolves its default). Upgrade to per-key insertion if a section's key set
    # grows in place and the file must list it; comment-preserving round-trip
    # would then want ruamel.yaml over the bare-pyyaml read used here.
    """
    _ensure_core_sections()
    target = path or _resolve_config_path()
    existing_text = ""
    if os.path.exists(target):
        with open(target, encoding="utf-8") as f:
            existing_text = f.read()
    present = _read(target)                    # which sections already exist
    out = existing_text if existing_text.strip() else _HEADER
    appended = [_render_section(section, keys)
                for section, keys in _REGISTRY.items() if section not in present]
    if appended:
        if out and not out.endswith("\n"):
            out += "\n"
        out += "\n".join(appended)
    os.makedirs(os.path.dirname(target) or ".", exist_ok=True)
    with open(target, "w", encoding="utf-8") as f:
        f.write(out)
    return target


# ── Spec 328 Slice 4 — doctor report + validation ─────────────────────────────
def config_report(*, path: str | None = None) -> dict:
    """Every registered key → ``{value, source}`` (env / file / default), so doctor
    can explain *why* a value is what it is. Secret keys are redacted to presence
    (``value`` is ``"set"``/``"unset"`` — the literal is never reported)."""
    _ensure_core_sections()
    secrets = set(secret_keys())
    out: dict = {}
    for dotted in registered_keys():
        r = config_resolve(dotted, path=path)
        if dotted in secrets:
            present = r["source"] == "env" and bool(r["value"])
            out[dotted] = {"value": "set" if present else "unset", "source": r["source"]}
        else:
            out[dotted] = {"value": r["value"], "source": r["source"]}
    return out


def config_validate(*, path: str | None = None) -> list[str]:
    """Config-health issues (empty = clean): a registered key resolving outside
    its declared ``enum``, and a key present in the file that no section
    registered (typo / stale). Each message names the key + the repair."""
    _ensure_core_sections()
    issues: list[str] = []
    for section, keys in _REGISTRY.items():
        for k in keys:
            if not k.enum:
                continue
            val = config_resolve(f"{section}.{k.name}", path=path)["value"]
            if val not in k.enum:
                issues.append(
                    f"config {section}.{k.name}={val!r} is invalid (expected "
                    f"{'|'.join(map(str, k.enum))}) — fix .agency/config.yaml or "
                    f"run `agency-doctor --write-config` to regenerate missing keys")
    registered = set(registered_keys())
    for section, sec in (_read(path or _resolve_config_path()) or {}).items():
        if isinstance(sec, dict):
            for name in sec:
                if f"{section}.{name}" not in registered:
                    issues.append(
                        f"config {section}.{name} in .agency/config.yaml is not a "
                        f"registered key (typo or stale?)")
    return issues


# ── core section (always registered) ──────────────────────────────────────────
register_config_section("core", [
    ConfigKey("db_path", "AGENCY_DB", ".agency/session.db",
              "central bi-temporal graph DB (Spec 020)"),
    ConfigKey("embedder", "AGENCY_EMBEDDER", "tfidf",
              "recall embedder backend", enum=("tfidf", "bge")),
    ConfigKey("token_backend", "AGENCY_TOKEN_BACKEND", "tiktoken",
              "token-count backend (anthropic|tiktoken|proxy)"),
])

# Secrets are env-only — the scaffold writes a ${env:VAR} reference, doctor
# reports presence, config_set never persists the literal (Spec 328 Q2).
register_config_section("secrets", [
    ConfigKey("jules_api_key", "JULES_API_KEY", "",
              "Jules remote-agent API key", secret=True),
    ConfigKey("anthropic_api_key", "ANTHROPIC_API_KEY", "",
              "Anthropic API key", secret=True),
])
