"""Setup for the Agency Plugin for Claude Code.

This is the "in setup" that maps the harness-in-harness MICRO-skills (the engine's
capability verbs) into MACRO-skills (the capabilities themselves) behind a single
`help` discovery surface. It is SELF-HOSTED: the manifest, the MCP-server
declaration, the marketplace catalogue, the `help` skill, and the `/agency:help`
command are all generated by DOGFOODING the plugin-development capability
(`plugin.scaffold` / `author_skill` / `author_command`) over the live registry —
the engine authors its own Claude Code plugin.

    python -m agency.install [root]   # write the install under `root`
"""
from __future__ import annotations

import json
import os
import sys

from .capabilities.plugin import author_command, author_skill, help_map
from .engine import Engine
from . import templates

NAME = "agency"
VERSION = "0.1.0"
DESCRIPTION = ("Harness-in-harness agency engine: code-mode capabilities "
               "(macroskills) over one provenance graph.")
DISPLAY_NAME = "Agency"
AUTHOR = "netzkontrast"
HOMEPAGE = "https://github.com/netzkontrast/agency"
REPOSITORY = "https://github.com/netzkontrast/agency"
LICENSE = "MIT"

HELP_DESC = ("Use when you need to discover the agency engine's capabilities "
             "(macroskills) and their verbs (the micro-skills).")
CMD_DESC = "Use when you want to list the agency capabilities and their verbs."
CMD_BODY = (
    "Map the agency engine's capabilities (macroskills) to their verbs "
    "(micro-skills). Use the plugin's `bin/agency` wrapper — it resolves the "
    "plugin venv + PYTHONPATH so the `agency` package is always importable "
    "(plain `python -m agency.cli` would fail in the user's project "
    "interpreter). Bootstrap an intent, then call the help verb with its id:\n\n"
    "    AGENCY=\"${CLAUDE_PLUGIN_ROOT}/bin/agency\"\n"
    "    iid=$(\"$AGENCY\" --db agency.db intent --purpose help "
    "--deliverable map --acceptance ok | python3 -c "
    "'import sys,json; print(json.load(sys.stdin)[\"intent_id\"])')\n"
    "    \"$AGENCY\" --db agency.db execute --code "
    "\"return await call_tool('capability_plugin_help', {'intent_id': '$iid'})\"\n"
)


def _manifest() -> dict:
    """The enriched `.claude-plugin/plugin.json` for Claude Code. Built on top of
    `templates.manifest_obj` (the dogfooded base shape) with the install-time
    fields a marketplace listing wants and a `userConfig` for `JULES_API_KEY`
    that the MCP server reads via `${user_config.jules_api_key}`."""
    m = templates.manifest_obj(NAME, VERSION, DESCRIPTION)
    m["displayName"] = DISPLAY_NAME
    m["author"] = {"name": AUTHOR}
    m["homepage"] = HOMEPAGE
    m["repository"] = REPOSITORY
    m["license"] = LICENSE
    m["userConfig"] = {
        "jules_api_key": {
            "type": "string",
            "title": "Jules API Key",
            "description": ("Optional. Needed only for the `jules` capability "
                            "(remote async coding agent). Get a key from "
                            "https://jules.google.com — Claude Code stores it "
                            "in your system keychain and exposes it to the "
                            "Agency MCP server as JULES_API_KEY."),
            "sensitive": True,
        }
    }
    return m


def _mcp_config() -> dict:
    """`.mcp.json` — the in-plugin MCP server declaration. Launches the Agency
    FastMCP engine in stdio mode via the bin/ wrapper, which picks the plugin's
    venv if present and falls back to the system Python. `${CLAUDE_PLUGIN_ROOT}`
    is the plugin install dir; `${CLAUDE_PLUGIN_DATA}` is the persistent data
    dir (survives plugin updates); `${user_config.jules_api_key}` is wired by
    the manifest's `userConfig`."""
    return {
        "mcpServers": {
            "agency": {
                "command": "${CLAUDE_PLUGIN_ROOT}/bin/agency-mcp",
                "args": [],
                "env": {
                    "PYTHONPATH": "${CLAUDE_PLUGIN_ROOT}",
                    "AGENCY_DB": "${CLAUDE_PLUGIN_DATA}/agency.db",
                    "JULES_API_KEY": "${user_config.jules_api_key}",
                },
            }
        }
    }


def _marketplace() -> dict:
    """`.claude-plugin/marketplace.json` — single-plugin marketplace catalogue
    (this repo IS its own marketplace). `source: "./"` means the plugin source
    IS the marketplace root, so `/plugin marketplace add netzkontrast/agency`
    + `/plugin install agency@agency` installs from this repo directly."""
    return {
        "name": NAME,
        "owner": {"name": AUTHOR},
        "plugins": [
            {
                "name": NAME,
                "source": "./",
                "version": VERSION,
                "description": DESCRIPTION,
                "homepage": HOMEPAGE,
                "license": LICENSE,
            }
        ],
    }


def generate(engine: Engine) -> dict[str, str]:
    """Produce the install files from the LIVE registry (so `help` always reflects
    the real capability set). Returns {relative_path: file_contents}."""
    reg = engine.registry
    caps = {n: list(reg.get(n).verbs) for n in reg.names()}
    help_doc = help_map(caps)["result"]["doc"]
    return {
        ".claude-plugin/plugin.json":      json.dumps(_manifest(), indent=2),
        ".claude-plugin/marketplace.json": json.dumps(_marketplace(), indent=2),
        ".mcp.json":                       json.dumps(_mcp_config(), indent=2),
        "skills/help/SKILL.md":            author_skill("help", HELP_DESC, help_doc)["result"],
        "commands/help.md":                author_command("help", CMD_DESC, CMD_BODY)["result"],
    }


def write(root: str) -> list[str]:
    engine = Engine(":memory:")
    try:
        files = generate(engine)
    finally:
        engine.memory.close()
    written = []
    for rel, content in files.items():
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(content)
        written.append(path)
    return written


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for p in write(target):
        print(p)
