"""Setup for the Agency Plugin for Claude Code.

This is the "in setup" that maps the harness-in-harness MICRO-skills (the engine's
capability verbs) into MACRO-skills (the capabilities themselves) behind a single
`help` discovery surface. It is SELF-HOSTED: the manifest, the MCP-server
declaration, the marketplace catalogue, the `help` skill, and the `/agency:help`
command are all generated by DOGFOODING the plugin-development capability
(`plugin.scaffold` / `author_skill` / `author_command`) over the live registry —
the engine authors its own Claude Code plugin.

Usage::

    python -m agency.install                       # regen manifest etc into the
                                                   # current install root
    python -m agency.install --scaffold-db         # also create .agency/ + the
                                                   # .gitattributes binary marker
                                                   # (Spec 020); idempotent
    python -m agency.install <root>                # write under <root> instead
                                                   # of the package's repo root

Per Spec 055 (pipx-only doctrine, 2026-06-03), the legacy
``bin/agency-install`` bash wrapper was removed; install happens via
``pipx install agency`` and this module is called manually when a
maintainer regenerates the plugin manifest. The Spec 020 ``.agency/``
scaffold lands in the user's PROJECT (CLAUDE_PROJECT_DIR when set,
else the call-site root) because that is where the runtime DB
resolves — see ``_scaffold_target``.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

from .capabilities.plugin import author_command, author_skill, help_map


# Spec 148 Slice 2 — documented per-skill command cap (Open Q4). Slice 3
# replaces the alpha-sort cap with an invocation-rank cap derived from the
# live graph; until then the deterministic alpha sort keeps the surface
# stable across installs.
AGENCY_SKILL_CMD_TOP_N = 12


def _skill_name_to_slug(name: str) -> str:
    """`develop.skill_walk` → `develop-skill-walk`; `session-driver-pass`
    stays the same. Filesystem-safe `[a-z0-9-]+`."""
    import re as _re
    s = name.lower()
    s = _re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s or "unknown"


def _generate_per_skill_commands(reg) -> dict[str, str]:
    """Walk every capability's `ontology.skills` dict; emit one
    `commands/agency-<slug>.md` per walkable skill, capped at the
    documented top-N. Each command body calls `develop.skill_walk`
    with the skill name + a short usage note.

    Slice 2 ordering: alphabetic by skill name (deterministic). Slice 3
    derives the rank from invocation count."""
    skill_names: list[str] = []
    for cap_name in sorted(reg.names()):
        cap = reg.get(cap_name)
        skills = getattr(getattr(cap, "ontology", None), "skills", {}) or {}
        for sk_name in skills:
            if isinstance(sk_name, str):
                skill_names.append(sk_name)
    skill_names = sorted(set(skill_names))
    picks = skill_names[:AGENCY_SKILL_CMD_TOP_N]
    out: dict[str, str] = {}
    for sk_name in picks:
        slug = _skill_name_to_slug(sk_name)
        # Skip when the slug would collide with the two static Slice 1
        # commands; doctrine: hand-authored wins (Spec 148 §"author
        # discipline").
        if slug in ("agency", "onboard"):
            continue
        path = f"commands/agency-{slug}.md"
        desc = (
            f"Walk the `{sk_name}` skill — `/agency-{slug}` drives "
            f"`develop.skill_walk(name='{sk_name}')` so the engine "
            f"delivers ONE phase at a time and records the SkillRun "
            f"provenance (Spec 018 Win 1)."
        )
        body = (
            f"## `/agency-{slug}` — walk `{sk_name}`\n\n"
            f"Drive the `{sk_name}` skill atomically (Spec 018) so each "
            f"phase records a `Phase` node + the SkillRun records `SERVES` "
            f"the active Intent. The engine pauses at hard gates; resume "
            f"with the gate's `resume_with` keys.\n\n"
            f"### How\n\n"
            f"```python\n"
            f"await call_tool('capability_develop_skill_walk', {{\n"
            f"    'name': '{sk_name}',\n"
            f"    'inputs': {{}},\n"
            f"}})\n"
            f"```\n\n"
            f"To resume after a paused gate, pass `resume_from='<skill_id>'` "
            f"and `inputs={{<gate.resume_with keys>}}`. The walker returns "
            f"the typed status contract: `completed | input-required | failed`.\n\n"
            f"### Derived\n\n"
            f"This command is auto-generated from the live capability "
            f"registry by `install.generate()` per Spec 148 Slice 2; "
            f"deleting it WILL NOT remove the skill, but the next install "
            f"rewrites the file from the live ontology.\n"
        )
        out[path] = author_command(f"agency-{slug}", desc, body)["result"]
    return out
from .engine import Engine
from . import templates

NAME = "agency"
VERSION = "0.1.0"
DESCRIPTION = ("Harness-in-harness agency engine: code-mode capabilities "
               "(macroskills) over one provenance graph.")
DISPLAY_NAME = "Agency"
AUTHOR = "netzkontrast"
HOMEPAGE = "https://github.com/netzkontrast/agency"
REPOSITORY = "https://github.com/netzkontrast/agency"
LICENSE = "MIT"

HELP_DESC = ("Use when you need to discover the agency engine's capabilities "
             "(macroskills) and their verbs (the micro-skills).")
CMD_DESC = "Use when you want to list the agency capabilities and their verbs."

# The MCP server this plugin installs surfaces three tools to Claude Code:
# `mcp__plugin_agency_agency__{search,get_schema,execute}`. When the skill
# is read inside Claude Code those are reachable in-process and should be
# the primary surface. The bash bootstrap remains for Jules / no-MCP
# harnesses (see AGENCY_PROTOCOL.md) — the engine is isomorphic over both.
HELP_ALLOWED_TOOLS = (
    "  - mcp__plugin_agency_agency__search\n"
    "  - mcp__plugin_agency_agency__get_schema\n"
    "  - mcp__plugin_agency_agency__execute\n"
    "  - Bash"
)

_MCP_QUICKSTART = (
    "## Quick start — MCP (Claude Code)\n\n"
    "The plugin installs an MCP server exposing the code-mode contract\n"
    "(`search` · `get_schema` · `execute`) AND three engine-substrate\n"
    "onboarding tools (Spec 029):\n\n"
    "- `agency_welcome` — one-shot onboarding payload; returns the\n"
    "  bootstrap example + the live capability list. **Start here.**\n"
    "- `agency_install` — scaffold `.agency/` + a CLAUDE.md snippet in\n"
    "  the current target repo. Idempotent.\n"
    "- `intent_bootstrap` — mint AND confirm an Intent. The only verb\n"
    "  that does not require an existing `intent_id`.\n"
    "- `agency_doctor` — health check (Spec 030): python version, deps,\n"
    "  DB reachability, JULES_API_KEY presence (never the value).\n"
    "  Call when something silently fails.\n\n"
    "These onboarding tools and the code-mode trio share one MCP server\n"
    "(`mcp__plugin_agency_agency__execute` for the sandbox, "
    "`mcp__plugin_agency_agency__search` for discovery, "
    "`mcp__plugin_agency_agency__get_schema` before a call).\n\n"
    "```python\n"
    "# 1. Onboard (one call; no intent_id needed)\n"
    "await call_tool('agency_welcome', {})\n\n"
    "# 2. Scaffold .agency/ + CLAUDE.md in the target repo if missing\n"
    "await call_tool('agency_install', {})\n\n"
    "# 3. Mint the intent every capability verb SERVES against\n"
    "r = await call_tool('intent_bootstrap', {\n"
    "    'purpose': 'ship X',\n"
    "    'deliverable': 'Y working',\n"
    "    'acceptance': 'tests green',\n"
    "})\n"
    "# 4. Use it\n"
    "await call_tool('capability_plugin_help', {'intent_id': r['intent_id']})\n"
    "```\n\n"
    "## Quick start — bash (Jules / no-MCP)\n\n"
    "The CLI resolves the graph DB itself (Spec 020: `AGENCY_DB` env, else\n"
    "`./.agency/session.db`) — do NOT pass `--db`, or the bash surface writes\n"
    "to a different store than MCP. The canonical entrypoint is\n"
    "`python -m agency.cli` (works in Jules / no-MCP / any context where the\n"
    "venv is activated). Spec 065: `agency` (the pipx-installed\n"
    "console-script) is the canonical CLI form — no bin/ shim.\n\n"
    "```bash\n"
    'iid=$(agency intent --purpose help --deliverable map --acceptance ok \\\n'
    '      | python3 -c \'import sys,json; print(json.load(sys.stdin)["intent_id"])\')\n'
    'agency execute --code \\\n'
    "  \"return await call_tool('capability_plugin_help', {'intent_id': '$iid'})\"\n"
    "```\n\n"
)

CMD_BODY = (
    _MCP_QUICKSTART
    + "## Slash-command bash fallback\n\n"
    "If the MCP server isn't reachable from your shell, use the\n"
    "pipx-installed `agency` console-script (Spec 055/065 — bin/ shims\n"
    "removed; rely on pipx for PATH resolution).\n"
    "Bootstrap an intent, then call the help verb with its\n"
    "id (no `--db` — the Spec 020 resolver picks `./.agency/session.db`,\n"
    "the same store MCP uses):\n\n"
    "    iid=$(agency intent --purpose help "
    "--deliverable map --acceptance ok | python3 -c "
    "'import sys,json; print(json.load(sys.stdin)[\"intent_id\"])')\n"
    "    agency execute --code "
    "\"return await call_tool('capability_plugin_help', {'intent_id': '$iid'})\"\n"
)

# Spec 148 Slice 1 — the `/agency` slash family.
# `/agency [query]` is the one-keystroke dispatcher: with a query it routes to
# tiered discovery (`mcp__agency__search`, Spec 068); bare it prints the live
# capability list via `agency_welcome` (Spec 029). The flat-family shape (vs a
# mega-command with subcommands) is Open-Q-1's recommendation — Claude Code
# lists each command, so discoverability wins.
AGENCY_CMD_DESC = (
    "Use when you want a one-keystroke entry to the agency engine — browse "
    "capabilities, run tiered discovery on a query, or see the live onboarding "
    "payload."
)
AGENCY_CMD_BODY = (
    "## `/agency [query]` — the agency dispatcher\n\n"
    "One-keystroke entry to the agency MCP surface (the `search` · "
    "`get_schema` · `execute` wire contract, Spec 029 / CORE.md).\n\n"
    "### With a query → tiered discovery\n\n"
    "When invoked with text, route it to the live capability graph via "
    "`mcp__agency__search` (tiered discovery, Spec 068):\n\n"
    "```python\n"
    "await call_tool('mcp__agency__search', "
    "{'query': '<your query>', 'detail': 'brief'})\n"
    "```\n\n"
    "Then drill into a found verb with `mcp__agency__get_schema` before "
    "calling it inside `mcp__agency__execute`.\n\n"
    "### Bare → the welcome payload\n\n"
    "When invoked with no argument, print the live capability list + the "
    "bootstrap example via `agency_welcome` (the canonical first call):\n\n"
    "```python\n"
    "await call_tool('agency_welcome', {})\n"
    "```\n\n"
    "`agency_welcome` returns the wire contract, the code-mode chaining "
    "example, the tier-0 capability map, and the resolved graph DB path — "
    "everything you need to start a session.\n\n"
    "### Next\n\n"
    "If no Intent is open yet, run `/agency-onboard` to capture one through "
    "a short describe → configure → confirm → capture interview.\n"
)

# `/agency-onboard` — the four-beat first-touch interview. Slice 1 ships the
# static prompt-list form (the agent reads the beats + drives the interview in
# chat, then derives intent_bootstrap fields from the answers). Slice 2 swaps
# in the Spec 147 AnthropicDriver-powered conversational version with each turn
# captured as an Artefact(kind="onboarding-turn") (the provenance round-trip).
AGENCY_ONBOARD_CMD_DESC = (
    "Use when starting fresh work in a repo and you want the agency engine to "
    "capture your intent through a short guided interview before any verb runs."
)
AGENCY_ONBOARD_CMD_BODY = (
    "## `/agency-onboard` — first-touch intent capture\n\n"
    "A short four-beat interview that turns 'what you want to do' into a "
    "graph-captured Intent every later capability verb SERVES against. The "
    "user stays creative; the engine captures everything (the GOALS.md "
    "provenance moat).\n\n"
    "### The four beats\n\n"
    "1. **describe** — ask the user what they want to ship in one sentence "
    "('a novel chapter', 'a token-economy lint', …). Capture the verbatim "
    "answer.\n"
    "2. **configure** — ask what 'done' looks like + any constraints "
    "(deadline, format, acceptance test). Capture it.\n"
    "3. **confirm** — read the captured purpose + deliverable back to the "
    "user and ask them to confirm or correct. Capture the confirmation.\n"
    "4. **capture** — call `intent_bootstrap` with `purpose` / `deliverable` "
    "/ `acceptance` DERIVED from the three captured answers (never invent "
    "fields the user didn't give):\n\n"
    "```python\n"
    "await call_tool('intent_bootstrap', {\n"
    "    'purpose': '<from beat 1>',\n"
    "    'deliverable': '<from beat 2>',\n"
    "    'acceptance': '<from beat 2/3>',\n"
    "})\n"
    "```\n\n"
    "### After capture\n\n"
    "The returned `intent_id` is the handle every capability verb takes. "
    "Walk a discipline skill next (`develop.brainstorm` for design, "
    "`develop.implement` for code) rather than improvising — the engine "
    "delivers one phase at a time so context stays bounded.\n\n"
    "If the user declines onboarding, do not re-prompt; the session can "
    "still mint an Intent later via `intent_bootstrap` directly.\n"
)


def _manifest() -> dict:
    """The enriched `.claude-plugin/plugin.json` for Claude Code. Built on top of
    `templates.manifest_obj` (the dogfooded base shape) with the install-time
    fields a marketplace listing wants and a `userConfig` for `JULES_API_KEY`
    that the MCP server reads via `${user_config.jules_api_key}`."""
    m = templates.manifest_obj(NAME, VERSION, DESCRIPTION)
    m["displayName"] = DISPLAY_NAME
    m["author"] = {"name": AUTHOR}
    m["homepage"] = HOMEPAGE
    m["repository"] = REPOSITORY
    m["license"] = LICENSE
    m["userConfig"] = {
        "jules_api_key": {
            "type": "string",
            "title": "Jules API Key",
            "description": ("Optional. Needed only for the `jules` capability "
                            "(remote async coding agent). Get a key from "
                            "https://jules.google.com — Claude Code stores it "
                            "in your system keychain and exposes it to the "
                            "Agency MCP server as JULES_API_KEY."),
            "sensitive": True,
        }
    }
    return m


def _mcp_config() -> dict:
    """`.mcp.json` — the in-plugin MCP server declaration. Launches the Agency
    FastMCP engine in stdio mode via the bin/ wrapper, which is a thin
    PATH router to the pipx-installed ``agency-mcp`` console-script
    (Spec 055 pipx-only doctrine).

    Path conventions:
    - ``${CLAUDE_PLUGIN_ROOT}`` — the plugin install dir (read-only code).
      Holds the bin/ launcher routers; survives plugin updates by design.
    - ``${CLAUDE_PROJECT_DIR}`` — the user's project root. Holds the graph
      DB so MCP + bash CLI converge on one store per project (the CLI
      defaults to ``./.agency/session.db`` via ``_db_path.resolve_db_path``;
      pointing AGENCY_DB at the same path is the unification — see
      reflection:9cd97a38 + tests/test_install_db_path.py).
    - ``${user_config.jules_api_key}`` — wired by the manifest's
      ``userConfig`` (secret).

    Previously this used ``${CLAUDE_PLUGIN_DATA}/agency.db`` (a path
    outside the project), which diverged from the CLI default and
    silently split observations between two stores. The plugin-data
    path is the right home for cross-project plugin state; the agency
    graph is per-project (the moat IS the graph; the graph lives with
    the project the agency is working on)."""
    return {
        "mcpServers": {
            "agency": {
                # Spec 065 (pipx-direct doctrine): the bare
                # `agency-mcp` command resolves from PATH, where pipx
                # install lands the console-script. Removes the
                # bin/agency-mcp shim (Specs 055/063 layered self-
                # detection + venv-first logic that PR #19 review
                # caught as fragile). Mirrors episodic-memory's bare
                # command pattern.
                "command": "agency-mcp",
                "args": [],
                # Spec 064: pin CWD to the project root so the MCP
                # subprocess's path resolver lands the graph DB in the
                # right place even if AGENCY_DB substitution fails.
                "cwd": "${CLAUDE_PROJECT_DIR}",
                "env": {
                    # Spec 061: PYTHONPATH removed under Spec 055
                    # pipx-only doctrine. agency-mcp resolves `agency`
                    # from its own pipx venv; PYTHONPATH would shadow
                    # the pipx-installed package with the plugin-tree
                    # source. AGENCY_DB + JULES_API_KEY stay (they're
                    # substrate config, not python-path config).
                    "AGENCY_DB": "${CLAUDE_PROJECT_DIR}/.agency/session.db",
                    "JULES_API_KEY": "${user_config.jules_api_key}",
                },
                # Spec 064: env_vars list declares which session env
                # vars Claude Code should pass through to the
                # subprocess. AGENCY_EMBEDDER (Spec 045 BGE opt-in)
                # would otherwise be silently dropped from the user's
                # shell env. Mirror of episodic-memory's pattern.
                "env_vars": [
                    "AGENCY_DB",
                    "AGENCY_EMBEDDER",
                    "JULES_API_KEY",
                ],
            }
        }
    }


def _marketplace_description(engine: Engine) -> str:
    """Spec 061 — dynamic description that names the live capability
    surface so a marketplace browser sees what actually ships.

    Concise form: ``<count> capabilities (<first 7 alphabetised>…)``.
    Computed from ``engine.registry.names()`` at generate-time so the
    description can never drift from the live registry.
    """
    caps = sorted(engine.registry.names())
    cap_sample = ", ".join(caps[:7])
    if len(caps) > 7:
        cap_sample += "…"
    return (
        f"Harness-in-harness agency engine: {len(caps)} self-registering "
        f"capabilities ({cap_sample}) over one provenance graph. "
        f"Code-mode IS the contract."
    )


def _marketplace(engine: Engine) -> dict:
    """`.claude-plugin/marketplace.json` — single-plugin marketplace catalogue
    (this repo IS its own marketplace). `source: "./"` means the plugin source
    IS the marketplace root, so `/plugin marketplace add netzkontrast/agency`
    + `/plugin install agency@agency` installs from this repo directly."""
    return {
        "name": NAME,
        "owner": {"name": AUTHOR},
        "plugins": [
            {
                "name": NAME,
                "source": "./",
                "version": VERSION,
                # Spec 061: live-derived description (per-cap surface
                # signal) rather than the static DESCRIPTION constant
                # — keeps the marketplace catalogue honest as the
                # capability surface grows.
                "description": _marketplace_description(engine),
                "homepage": HOMEPAGE,
                "license": LICENSE,
            }
        ],
    }


# Spec 062 + Spec 064 — SessionStart hook with cross-platform
# polyglot wrapper (run-hook.cmd) + matcher + async: false.
# The matcher excludes `compact` so the install loop doesn't fire
# every time the session compacts. The polyglot wrapper handles
# Windows + Unix from one command entry; extensionless script
# avoids Claude Code's `.sh` auto-bash-prepend on Windows.
#
# Spec 065 (PR #19 round-3 P2 PRRT_kwDOSj5Qos6HSqkH): the command
# substitution layer does NOT honor bash parameter-expansion syntax
# (`${VAR:-default}`), so we use the documented `${CLAUDE_PLUGIN_ROOT}`
# token directly. Non-Claude harnesses (Cursor/Codex) that don't set
# this var also won't run hooks via the Claude Code launcher, so the
# token-only form is correct.
# Spec 076 — the unified event dispatcher. Claude Code has NO top-level wildcard
# hook (one block per event name), so "unity" = every capture event invokes the
# SAME `dispatch` script, which pipes the event JSON to `agency hook` → the
# engine's single hook-handler surface. SessionStart KEEPS its specialized
# install hook (bootstrap, not capture). `async: true` keeps capture off the
# critical path; tool/subagent events carry a matcher, the rest always fire.
# AGENCY-DRIFT: hook-events — keep these event lists synced with the dispatcher
#   + Spec 076; new captured events plug in here, NOT via a new script.
_DISPATCH_CMD = "\"${CLAUDE_PLUGIN_ROOT}/hooks/run-hook.cmd\" dispatch"
_SESSION_START_CMD = "\"${CLAUDE_PLUGIN_ROOT}/hooks/run-hook.cmd\" session-start"
_DISPATCH_MATCHER_EVENTS = ("PreToolUse", "PostToolUse", "SubagentStop")
_DISPATCH_PLAIN_EVENTS = ("UserPromptSubmit", "Stop", "SessionEnd")


def _build_hooks_json() -> str:
    """Build hooks/hooks.json. Spec 280 sets per-event async flags per
    the doctrine table (sync for SessionStart / PreToolUse /
    UserPromptSubmit; async for the rest)."""
    from agency._hooks import ASYNC_BY_EVENT
    hooks: dict = {
        "SessionStart": [
            {
                "matcher": "startup|resume|clear",
                "hooks": [{"type": "command", "command": _SESSION_START_CMD,
                           "async": ASYNC_BY_EVENT.get("SessionStart", False)}],
            }
        ]
    }
    for ev in _DISPATCH_MATCHER_EVENTS:
        entry = {"type": "command", "command": _DISPATCH_CMD,
                 "async": ASYNC_BY_EVENT.get(ev, True)}
        hooks[ev] = [{"matcher": "*", "hooks": [entry]}]
    for ev in _DISPATCH_PLAIN_EVENTS:
        entry = {"type": "command", "command": _DISPATCH_CMD,
                 "async": ASYNC_BY_EVENT.get(ev, True)}
        hooks[ev] = [{"hooks": [entry]}]
    return json.dumps({"hooks": hooks}, indent=2) + "\n"


_SESSION_START_HOOKS_JSON = _build_hooks_json()


# Spec 076 + Spec 280 — the dispatcher script (extensionless, run via
# run-hook.cmd dispatch). Reads the hook event JSON on stdin and:
#   1. forwards it to `agency hook` so an Event node lands in the graph
#      (Spec 076), and
#   2. emits Slice 1 routing-advice hints on stderr when the payload is
#      a PreToolUse on Bash with a verb-equivalent command (`git commit`
#      -> `branch.commit_smart`, `pytest` -> `develop.test`) or an
#      Edit/Write on `Plan/*/spec.md` (-> `dogfood.observe`). Advisory
#      only (exit 0); Slice 2 flips the clearest routes to exit 2.
# Best-effort throughout: a missing CLI or python3 must NEVER break
# the session.
_DISPATCH_HOOK_SCRIPT = """\
#!/usr/bin/env bash
# agency unified event dispatcher (Spec 076 + Spec 280 Slice 1 routing).
set -u

PAYLOAD="$(cat || true)"

# Best-effort Event recording (Spec 076) + injection (Spec 292). `agency hook`
# prints an `inject` context block to STDOUT for UserPromptSubmit (the
# assumption-guard that wires in intent + thinking) and nothing for other
# events — so passing STDOUT through is safe and surfaces the guard to the
# prompt. Provenance noise stays on STDERR (dropped).
if command -v agency >/dev/null 2>&1; then
  printf '%s' "${PAYLOAD}" | agency hook 2>/dev/null || true
fi

# Routing advice (Spec 280 Slice 1) — parse the payload via Python so
# we don't pull in jq as a dependency.
if command -v python3 >/dev/null 2>&1; then
  printf '%s' "${PAYLOAD}" | python3 -c '
import json, re, sys
try:
    payload = json.load(sys.stdin)
except Exception:
    sys.exit(0)
event = str(payload.get("hook_event_name") or "")
tool  = str(payload.get("tool_name") or "")
tin   = payload.get("tool_input") or {}
def hint(msg):
    print("agency hook | " + msg, file=sys.stderr)
if event == "PreToolUse" and tool == "Bash":
    cmd = str(tin.get("command") or "").strip()
    head = cmd.split()[0] if cmd else ""
    if cmd.startswith("git commit") or cmd.startswith("git push"):
        verb = ("branch.commit_smart" if cmd.startswith("git commit")
                else "branch.finish_branch")
        hint("raw `" + head + "` bypasses provenance — prefer "
             "`mcp__agency__execute` calling `" + verb + "(...)` so the "
             "commit/push records an Invocation + SERVES the active intent.")
    elif (cmd.startswith("pytest") or cmd.startswith("python -m pytest")
          or cmd.startswith("python3 -m pytest")):
        hint("raw `pytest` bypasses provenance — prefer "
             "`develop.test(scope=...)` so the run records an Invocation. "
             "For fast iteration use `scripts/test-cap <marker>`.")
if event == "PreToolUse" and tool in ("Edit", "Write"):
    path = str(tin.get("file_path") or "")
    if re.search(r"(^|/)Plan/\\d{3}-[^/]+/spec\\.md$", path):
        hint("editing a spec file directly (" + path + ") leaves no "
             "provenance trail — pair with `dogfood.observe(scope=\\"spec\\", "
             "text=\\"what changed and why\\")` so the amendment is "
             "traceable via Spec 150 amendment-classifier.")
' || true
fi

exit 0
"""


# Spec 021 — the single engine Monitor channel. ONE monitors.json entry; every
# capability fans its events into .agency/monitor.log via ctx.emit_monitor.
# The path MUST match where `Engine.monitor` actually writes: the engine
# resolves the log as a sibling of the session DB, and `.mcp.json` sets
# AGENCY_DB=${CLAUDE_PROJECT_DIR}/.agency/session.db — so the live log is
# ${CLAUDE_PROJECT_DIR}/.agency/monitor.log. `${CLAUDE_PROJECT_DIR:-.}` shell
# default-expansion covers local-dev (var unset → ./.agency/monitor.log)
# without a dead `|| tail` branch (tail -F retries forever and never exits to
# the `||`). `-n 0` starts at end-of-file so a fresh session does NOT replay
# stale `completed`/`warning` history as if it just happened.
# AGENCY-DRIFT: monitor-channel — this is the lone monitor surface; new
#   event sources plug in via emit_monitor, NOT a new monitors.json entry.
_MONITORS_JSON = json.dumps([
    {
        "name": "agency-engine",
        "command": 'tail -n 0 -F "${CLAUDE_PROJECT_DIR:-.}/.agency/monitor.log"',
        "description": "Agency engine event stream — capability events fan in here.",
    }
], indent=2) + "\n"


# Spec 064 — polyglot CMD+bash wrapper. Valid as both a Windows CMD
# batch (the heredoc-delimited block runs first) and a bash script
# (the `:` is a no-op label so `: << 'CMDBLOCK'` reads as a here-doc
# CMD treats as a `:label` directive). Verbatim port of the canonical
# Superpowers 5.1.0 wrapper; the only customisation is the script-
# name passthrough at the tail.
_RUN_HOOK_CMD_SCRIPT = """\
: << 'CMDBLOCK'
@echo off
REM Cross-platform polyglot wrapper for hook scripts (Spec 064).
REM On Windows: cmd.exe runs the batch portion, which finds and calls bash.
REM On Unix: the shell interprets this as a script (: is a no-op in bash).
REM
REM Hook scripts use extensionless filenames (e.g. "session-start" not
REM "session-start.sh") so Claude Code's Windows auto-detection -- which
REM prepends "bash" to any command containing .sh -- doesn't interfere.
REM
REM Usage: run-hook.cmd <script-name> [args...]

if "%~1"=="" (
    echo run-hook.cmd: missing script name >&2
    exit /b 1
)

set "HOOK_DIR=%~dp0"

REM Try Git for Windows bash in standard locations
if exist "C:\\Program Files\\Git\\bin\\bash.exe" (
    "C:\\Program Files\\Git\\bin\\bash.exe" "%HOOK_DIR%%~1" %2 %3 %4 %5 %6 %7 %8 %9
    exit /b %ERRORLEVEL%
)
if exist "C:\\Program Files (x86)\\Git\\bin\\bash.exe" (
    "C:\\Program Files (x86)\\Git\\bin\\bash.exe" "%HOOK_DIR%%~1" %2 %3 %4 %5 %6 %7 %8 %9
    exit /b %ERRORLEVEL%
)

REM Try bash on PATH (e.g. user-installed Git Bash, MSYS2, Cygwin)
where bash >nul 2>nul
if %ERRORLEVEL% equ 0 (
    bash "%HOOK_DIR%%~1" %2 %3 %4 %5 %6 %7 %8 %9
    exit /b %ERRORLEVEL%
)

REM No bash found - exit silently rather than error
REM (plugin still works, just without SessionStart auto-install)
exit /b 0
CMDBLOCK

# Unix: run the named script directly
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SCRIPT_NAME="$1"
shift
exec bash "${SCRIPT_DIR}/${SCRIPT_NAME}" "$@"
"""


_SESSION_START_HOOK_SCRIPT = """\
#!/usr/bin/env bash
# agency SessionStart hook — Spec 062 + Spec 065 (pipx-direct doctrine).
#
# Single install path: `pipx install --editable ${CLAUDE_PLUGIN_ROOT}`.
# Scaffolds the project's .agency/ EVERY session (idempotent), then
# installs the MCP server via pipx if not already on PATH.
#
# Spec 065 supersedes Spec 063's three-step fallback chain (PR #19
# review surfaced 4 correctness issues with the pip --user and
# .agency/.venv fallback paths). Rely on pipx; print a clear hint
# when it's missing so the user can install it once and retry.
#
# Two ordering rules (closes PR #19 P1 + P2):
#  - Scaffold runs BEFORE the install-check early-exit, so already-
#    installed users get .agency/ in a fresh project on first session.
#  - Scaffold uses `agency install --scaffold-only` (NOT --scaffold-db)
#    so we never write the plugin's .mcp.json/hooks/skills/commands
#    INTO the user's project repo. --scaffold-only writes the
#    .agency/ dir + .gitattributes binary marker, nothing else.
set -e

# --- Spec 292: refresh the repo index as a Document on session start ---
# Regenerates PROJECT_INDEX.md (a RepoIndex graph node — the 94%-reduction
# briefing) via the ported `develop index` verb, so every session opens with a
# fresh, token-cheap map of the repo. BACKGROUNDED + non-fatal: never blocks
# session start; deterministic + content-hash stable, so it does not churn git
# when nothing changed. AGENCY_INDEX_ON_START=0 opts out.
_agency_index_on_start() {
  [ "${AGENCY_INDEX_ON_START:-1}" = "0" ] && return 0
  [ -n "${CLAUDE_PROJECT_DIR:-}" ] && command -v agency >/dev/null 2>&1 || return 0
  ( cd "${CLAUDE_PROJECT_DIR}" && agency execute --code "iid = (await call_tool('intent_bootstrap', {'purpose':'session-start repo index','deliverable':'PROJECT_INDEX.md','acceptance':'RepoIndex node recorded'}))['intent_id']
await call_tool('capability_develop_index', {'intent_id': iid, 'agent_id':'agent:session-start', 'path':'.', 'apply': True})
return 'ok'" >/dev/null 2>&1 & ) || true
}

# --- Scaffold the project's .agency/ (idempotent; runs every session) ---
# Only reachable if agency-mcp is already installed; the post-install
# block below covers the first-run case.
if [ -n "${CLAUDE_PROJECT_DIR:-}" ] && command -v agency >/dev/null 2>&1; then
  agency install --scaffold-only "${CLAUDE_PROJECT_DIR}" >&2 || \\
    echo "agency: .agency/ scaffold failed (non-fatal)" >&2
fi

# --- Idempotent install guard: bail if agency-mcp is already on PATH. ---
if command -v agency-mcp >/dev/null 2>&1; then
  _agency_index_on_start
  exit 0
fi

# Single install path: pipx. No pip --user. No per-project venv.
if ! command -v pipx >/dev/null 2>&1; then
  cat >&2 <<'HINT'
agency: pipx is required but not on PATH.

Install pipx once (https://pipx.pypa.io/stable/installation/), then
restart your session. The hook will auto-install agency.

    python3 -m pip install --user pipx
    python3 -m pipx ensurepath
    # restart shell or `source ~/.bashrc`, then restart Claude Code
HINT
  # Don't block session start; MCP boot prints its own missing-binary
  # hint when the user tries the first verb.
  exit 0
fi

echo "agency: installing via pipx (one-time) — this may take ~5s" >&2
if ! pipx install --editable "${CLAUDE_PLUGIN_ROOT}" >&2; then
  echo "agency: pipx install failed (non-fatal — see output above)" >&2
  exit 0
fi

# PR #19 round-3 P2 (PRRT_kwDOSj5Qos6HSqkN): pipx installs scripts
# into ${PIPX_BIN_DIR} (default ~/.local/bin), but that dir may not
# yet be on PATH in this session if the user hasn't run
# `pipx ensurepath` + restarted the shell. Probe pipx's bin dir and
# prepend it to PATH for THIS process so the immediate scaffold call
# resolves; also run `pipx ensurepath` so future sessions inherit it.
PIPX_BIN_DIR="$(pipx environment --value PIPX_BIN_DIR 2>/dev/null || echo "${HOME}/.local/bin")"
case ":${PATH}:" in
  *":${PIPX_BIN_DIR}:"*) ;;
  *) export PATH="${PIPX_BIN_DIR}:${PATH}" ;;
esac
pipx ensurepath >/dev/null 2>&1 || true

# Hard-validate that agency-mcp is actually reachable now. If pipx
# install reported success but the script isn't resolvable, surface
# an actionable error pointing at `pipx ensurepath` + shell restart.
if ! command -v agency-mcp >/dev/null 2>&1; then
  cat >&2 <<HINT
agency: pipx install succeeded but agency-mcp is not on PATH.
Pipx put it under: ${PIPX_BIN_DIR}

Add that dir to PATH and restart your session:
    pipx ensurepath
    # then restart shell / Claude Code
HINT
  exit 0
fi

# After first-time install: scaffold the target repo's .agency/ via
# the pipx-installed agency CLI. --scaffold-only never touches the
# user's .mcp.json / hooks/ / skills/ / commands/ (PR #19 P1 fix).
if [ -n "${CLAUDE_PROJECT_DIR:-}" ]; then
  agency install --scaffold-only "${CLAUDE_PROJECT_DIR}" >&2 || \\
    echo "agency: .agency/ scaffold failed (non-fatal)" >&2
fi

# Refresh the repo index now that the CLI is installed (Spec 292).
_agency_index_on_start

exit 0
"""


# Spec 064 — using-agency meta-skill. Broad trigger ("any agency-
# related task starts here") + a chain example that names the two
# bootstrap calls every session must make. Modelled on
# `using-superpowers` from Superpowers 5.1.0.
_USING_AGENCY_SKILL_MD = """\
---
name: using-agency
description: Use when starting any conversation that may touch the agency engine (capabilities, intents, provenance, MCP code-mode) — bootstrap an Intent via agency_welcome BEFORE invoking any agency verb.
allowed-tools:
  - mcp__plugin_agency_agency__execute
  - mcp__plugin_agency_agency__search
  - mcp__plugin_agency_agency__get_schema
---

# using-agency

The entry skill the orchestrator MUST invoke before calling any agency
capability verb. Modelled on the `using-superpowers` pattern: a broad-
trigger skill that primes the canonical bootstrap chain.

## The two-step bootstrap (load-bearing)

**Every agency-related task starts with the same two calls.** No
exceptions:

1. `agency_welcome` — returns the canonical bootstrap example + the
   live capability list + the resolved `.agency/` DB path. This IS
   the first call of every session.
2. `intent_bootstrap(purpose=, deliverable=, acceptance=)` — mints
   AND confirms the Intent that EVERY subsequent verb will SERVE.

```python
# Inside an MCP execute block:
welcome = await call_tool("agency_welcome", {})
# Read welcome["capabilities"] for the live verb surface, then:
i = await call_tool("intent_bootstrap", {
    "purpose":     "<one-line why>",
    "deliverable": "<one-line what>",
    "acceptance":  "<one-line how to verify>"
})
intent_id = i["intent_id"]
# Now any capability verb is reachable:
r = await call_tool("capability_<cap>_<verb>", {"intent_id": intent_id, ...})
```

## Why both calls are required

- **`agency_welcome`** is pure introspection (no graph writes). It
  returns the discoverable surface — without it, the agent has to
  guess capability names.
- **`intent_bootstrap`** records the orchestrator's why/what/accept
  triple as an `Intent` node. Every later verb call writes an
  `Invocation` that `SERVES` this Intent. The cross-concern
  provenance traversal starts here — skip it and the engine treats
  your calls as orphaned activity.

## When this skill applies (broad trigger)

- The user mentions "agency", "capability", "intent", "verb",
  "provenance", "dispatch", "Jules", "research", "analyze", "explain",
  "reflect"…
- The user asks the orchestrator to do anything in a repo where
  `.agency/` exists.
- A fresh session starts and any MCP code-mode block is about to call
  a `capability_*` tool.
- The user asks for a status/health check on the substrate
  (`agency_doctor`).

**When in doubt, invoke `agency_welcome` first.** Cheap (sub-1KB
return) + cancellable; nothing else stands between a stale start and
a clean dispatch.

## Failure modes the skill prevents

| Symptom | Root cause (this skill closes it) |
|---|---|
| `error: intent_id required` from a verb call | Skipped `intent_bootstrap` |
| `unknown capability` | Skipped `agency_welcome` — guessed name |
| Orphaned Invocation (no SERVES edge) | Verb called outside the intent flow |
| `.agency/session.db` missing on first call | SessionStart hook hadn't finished — re-call `agency_welcome` which surfaces the resolved path |

## See also

- `agency_doctor` — health-check substrate tool when something silently fails.
- `skills/help/SKILL.md` — the live capability map (regenerated by
  `agency install`).
- `dispatch-decision` — once an intent exists, this skill decides
  inline vs subagent/Jules.
"""


def generate(engine: Engine) -> dict[str, str]:
    """Produce the install files from the LIVE registry (so `help` always reflects
    the real capability set). Returns {relative_path: file_contents}.

    The `help` skill body is `_MCP_QUICKSTART` (MCP-first, bash-fallback)
    PREPENDED to the auto-discovered capability map from `plugin.help_map`.
    Two surfaces in one skill so MCP-equipped (Claude Code) and bash-only
    (Jules) harnesses both find their idiomatic call shape — the canon's
    isomorphism guarantee landing in the install artefacts.

    Spec 031 Phase 2 / Spec 032 §G — per-capability emit pipeline.
    For every registered capability that declares a ``skill_doc``, the
    per-capability emit pipeline (``skill_emit.emit_skill`` /
    ``emit_references`` / ``emit_bash_wrappers``) layers ITS files on
    top of the 5 legacy fixed files. Caps without ``skill_doc`` are
    skipped (Phase 4 will migrate them); the legacy ``skills/help``
    surface remains the discovery shortcut until that flip."""
    reg = engine.registry
    caps = {n: list(reg.get(n).verbs) for n in reg.names()}
    help_doc = help_map(caps)["result"]["doc"]
    skill_body = _MCP_QUICKSTART + "\n" + help_doc
    # Spec 302 — stamp the live capability-set hash into the manifest so
    # `agency_doctor.surface_freshness` can detect a stale installed surface.
    from ._envelope import capability_set_hash
    manifest = _manifest()
    manifest["_surface_hash"] = capability_set_hash(list(reg.names()))
    files: dict[str, str] = {
        ".claude-plugin/plugin.json":      json.dumps(manifest, indent=2),
        ".claude-plugin/marketplace.json": json.dumps(_marketplace(engine), indent=2),
        ".mcp.json":                       json.dumps(_mcp_config(), indent=2),
        # Spec 062 — SessionStart hook auto-runs `pipx install` on
        # first session so marketplace consumers (especially Claude
        # Code Web environments) don't hit the .mcp.json shim's
        # exit-127 silent failure on a fresh install.
        "hooks/hooks.json":                _SESSION_START_HOOKS_JSON,
        # Spec 021 — single engine Monitor channel (one surface, many emitters).
        "monitors/monitors.json":          _MONITORS_JSON,
        # Spec 064: cross-platform polyglot wrapper + extensionless
        # hook script (so Windows doesn't auto-prepend `bash` to a `.sh`
        # filename and break on systems without bash on PATH).
        "hooks/run-hook.cmd":              _RUN_HOOK_CMD_SCRIPT,
        "hooks/session-start":             _SESSION_START_HOOK_SCRIPT,
        # Spec 076 — the unified event dispatcher (run via run-hook.cmd dispatch).
        "hooks/dispatch":                  _DISPATCH_HOOK_SCRIPT,
        # Spec 064: using-agency meta-skill (broad-trigger). Tells the
        # orchestrator to call agency_welcome + intent_bootstrap before
        # any capability verb — mirrors using-superpowers' pattern.
        "skills/using-agency/SKILL.md":    _USING_AGENCY_SKILL_MD,
        "skills/help/SKILL.md":            author_skill(
            "help", HELP_DESC, skill_body,
            allowed_tools=HELP_ALLOWED_TOOLS,
        )["result"],
        "commands/help.md":                author_command("help", CMD_DESC, CMD_BODY)["result"],
        # Spec 148 Slice 1 — the /agency slash family. Authored through the
        # same plugin.author_command boundary that builds /help, so the
        # frontmatter shape stays consistent (dogfooding the plugin cap).
        "commands/agency.md":              author_command(
            "agency", AGENCY_CMD_DESC, AGENCY_CMD_BODY)["result"],
        "commands/agency-onboard.md":      author_command(
            "agency-onboard", AGENCY_ONBOARD_CMD_DESC, AGENCY_ONBOARD_CMD_BODY)["result"],
    }
    # Spec 148 Slice 2 — per-skill /agency-<skill> shortcuts. Derived from
    # the live capability registry's `ontology.skills`, capped at the
    # documented top-N (Open Q4 — 60 live skills would crowd the palette).
    # Slice 3 swaps the alpha-sort cap for an invocation-rank cap.
    for path, content in _generate_per_skill_commands(reg).items():
        files[path] = content
    # Spec 031 §F / Spec 032 §G — per-capability emit pipeline.
    # NOTE on cache: cache.peek operates on the filesystem, but generate()
    # doesn't have a root yet (write() does). Task 2.5 design: cache check
    # happens in write(), not generate(). For generate(), always emit fresh.
    from .skill_emit import (
        emit_skill, emit_references, emit_bash_wrappers,
        _capability_hash, GEN_VERSION,
    )
    from . import cache as _cache  # noqa: F401 — reserved for future write()-side cache check
    for cap_name in reg.names():
        cap = reg.get(cap_name)
        if getattr(cap, "skill_doc", None) is None:
            continue  # cap lacks skill_doc → can't render SKILL.md (Phase 4 will fix)
        _hash = _capability_hash(cap, GEN_VERSION)  # reserved for write()-side cache.peek
        files.update(emit_skill(cap_name, cap.skill_doc, cap.verbs,
                                getattr(cap.ontology, "skills", None)))
        files.update(emit_references(cap_name, cap.verbs))
        files.update(emit_bash_wrappers(cap_name, cap.verbs))
    return files


def write(root: str) -> list[str]:
    """Generate + write the install files under ``root``. Returns the list of
    absolute paths that were written.

    Spec 032 §8a: bash wrappers under ``bin/`` get ``chmod 0o755`` to mark
    them executable. On read-only mounts (Windows network shares, locked
    container layers) the chmod call raises ``OSError``; we surface a
    single warning per file to stderr and continue — the file content is
    still on disk, the user can re-run ``chmod +x`` themselves."""
    engine = Engine(":memory:")
    try:
        files = generate(engine)
        cap_names = list(engine.registry.names())
    finally:
        engine.memory.close()
    # Spec 092 G1 — prune generator-owned files that no longer correspond to a live verb
    # (the installer historically WROTE but never PRUNED, so a removed/renamed verb left
    # an orphan bin wrapper / reference that check-drift didn't catch).
    pruned = _prune_orphans(root, set(files), cap_names)
    written: list[str] = []
    chmod_warnings: list[str] = []
    for rel, content in files.items():
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(content)
        # Spec 032 §8a + Spec 062 — chmod +x for bash wrappers and
        # hook scripts; graceful degrade on RO mount.
        if (rel.startswith("bin/")
                or rel.startswith("hooks/")    # Spec 064 — any file under hooks/
                or rel.endswith(".sh")):
            try:
                os.chmod(path, 0o755)
            except OSError as e:
                chmod_warnings.append(
                    f"chmod +x failed for {path!r} ({e}); "
                    f"users must `chmod +x` manually"
                )
        written.append(path)
    if chmod_warnings:
        for w in chmod_warnings:
            print(f"WARNING: {w}", file=sys.stderr)
    for p in pruned:
        print(f"pruned stale {p}", file=sys.stderr)
    return written


def _prune_orphans(root: str, expected: set[str], cap_names: list[str]) -> list[str]:
    """Spec 092 G1 — delete generator-owned files no longer in the generated set, scoped
    to the two fully-owned namespaces so nothing hand-authored is ever touched:
    ``bin/agency-<cap>-*`` per-verb wrappers (only for a LIVE capability) and
    ``skills/<cap>/references/*.md``.
    """
    from .skill_emit import _skill_name

    pruned: list[str] = []
    bin_prefixes = tuple(f"agency-{c}-" for c in cap_names)
    bindir = os.path.join(root, "bin")
    if os.path.isdir(bindir):
        for fn in sorted(os.listdir(bindir)):
            rel = f"bin/{fn}"
            if fn.startswith(bin_prefixes) and rel not in expected:
                try:
                    os.remove(os.path.join(bindir, fn))
                    pruned.append(rel)
                except OSError:
                    pass
    for cap in cap_names:
        refdir = os.path.join(root, "skills", _skill_name(cap), "references")
        if not os.path.isdir(refdir):
            continue
        for fn in sorted(os.listdir(refdir)):
            rel = f"skills/{_skill_name(cap)}/references/{fn}"
            if rel not in expected:
                try:
                    os.remove(os.path.join(refdir, fn))
                    pruned.append(rel)
                except OSError:
                    pass
    return pruned


def main(argv: list | None = None) -> int:
    """CLI entrypoint: regenerate the Claude Code plugin install files.

    Reusable from tests: pass an explicit ``argv`` list to bypass
    ``sys.argv`` parsing. Returns the process exit code (0 on success).

    Spec 031 Task 2.5 — adds ``--dry-run`` which builds the file map via
    ``generate()`` (running PRE-emit lint as a side effect) and prints the
    paths that WOULD be written + an ``OK`` status. Touches nothing on
    disk. Lint failures raise ``ValueError`` from ``emit_skill``, which
    propagates out as a non-zero exit (uncaught, by design)."""
    parser = argparse.ArgumentParser(
        prog="python -m agency.install",
        description="Regenerate the Claude Code plugin install files.",
    )
    parser.add_argument("root", nargs="?", default=None,
                        help="install root (default: this repo's root)")
    parser.add_argument("--scaffold-db", action="store_true",
                        help="also create .agency/ + .gitattributes binary marker (Spec 020)")
    parser.add_argument("--scaffold-only", action="store_true",
                        help="scaffold .agency/ + .gitattributes ONLY — do NOT write "
                             "the plugin install surface into the target (Spec 065 — "
                             "PR #19 P1: avoid overwriting a project's .mcp.json/hooks/ "
                             "when the SessionStart hook calls us with CLAUDE_PROJECT_DIR)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print the would-write paths + per-file lint result; "
                             "touch nothing on disk. Exit 0 iff all lints pass.")
    parser.add_argument("--patch-claude-settings",
                        action="store_true",
                        help="Spec 280 — write/merge the agency plugin entry "
                             "into the user's `.claude/settings.json` (and "
                             "wrap foreign hooks via shell.run). Idempotent; "
                             "creates `.bak` on first run.")
    parser.add_argument("--claude-settings-path",
                        default=None,
                        help="Override the path to `.claude/settings.json` "
                             "(default: $CLAUDE_PROJECT_DIR/.claude/"
                             "settings.json, or $PWD/.claude/settings.json "
                             "when the env var is unset).")
    ns = parser.parse_args(argv)
    target = ns.root or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if ns.dry_run:
        # generate() runs the PRE-emit lint via emit_skill; a lint failure
        # raises ValueError before any path is reported (good — no false OK).
        engine = Engine(":memory:")
        try:
            files = generate(engine)
        finally:
            engine.memory.close()
        for rel in files:
            print(f"{os.path.join(target, rel)} OK")
        return 0
    if ns.scaffold_only:
        # Spec 065 — scaffold the project's .agency/ WITHOUT writing the
        # plugin install surface into it (the SessionStart hook calls us
        # with target = ${CLAUDE_PROJECT_DIR}; we must not overwrite the
        # user's own .mcp.json / hooks/ / skills/ / commands/).
        scaffold_root = target
        result = scaffold_db(scaffold_root)
        for p in result["written"]:
            print(p)
        if result["gitattributes_updated"]:
            print(os.path.join(scaffold_root, ".gitattributes"))
        return 0
    # Codex review on PR #138 round 2: when `--patch-claude-settings`
    # is used WITHOUT a target root, the user wants their PROJECT
    # settings patched — running `write(target)` would also emit
    # `.mcp.json` / `hooks/` / `skills/` / `commands/` into the
    # project (the overwrite scenario `--scaffold-only` already
    # avoids). So when the user is ONLY patching settings (no
    # explicit `<root>` AND no `--scaffold-db`), skip the plugin
    # regen step.
    settings_only = bool(ns.patch_claude_settings and not ns.root
                         and not ns.scaffold_db)
    if not settings_only:
        for p in write(target):
            print(p)
    if ns.patch_claude_settings:
        from agency._hooks import patch_settings_file
        # Codex review on PR #138 round 2: the default settings path
        # is the PROJECT's `.claude/settings.json` — `$CLAUDE_PROJECT_DIR`
        # (set by Claude Code) or `$PWD` as a fallback. Defaulting to
        # `<root>/.claude/settings.json` in a pipx/site-packages
        # install would create the file under the package tree where
        # Claude Code never reads it.
        project_dir = (
            os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd())
        settings_path = (
            ns.claude_settings_path
            or os.path.join(project_dir, ".claude", "settings.json"))
        try:
            result = patch_settings_file(settings_path)
        except ValueError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 1
        print(f"patched: {result['settings_path']}")
        if result.get("backup_path"):
            print(f"backup: {result['backup_path']}")
        if result.get("wrapped_count"):
            print(f"wrapped {result['wrapped_count']} foreign hook(s)")
    if ns.scaffold_db:
        # The DB lives in the PROJECT, not the plugin root — scaffold there.
        scaffold_root = _scaffold_target(target)
        result = scaffold_db(scaffold_root)
        for p in result["written"]:
            print(p)
        if result["gitattributes_updated"]:
            print(os.path.join(scaffold_root, ".gitattributes"))
    # Spec 292 C5 (config completeness): after a plain install, if the plugin
    # isn't enabled in the project's settings, OFFER the one-liner fix instead
    # of leaving the user to discover `--patch-claude-settings`. Skipped when the
    # user already passed it (the patch ran above).
    if not ns.patch_claude_settings:
        project_dir = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
        settings_path = os.path.join(project_dir, ".claude", "settings.json")
        if not _plugin_enabled_in_settings(settings_path):
            print("\nNEXT: enable the agency plugin in this project — run:")
            print("  python -m agency.install --patch-claude-settings")
    return 0


def _plugin_enabled_in_settings(settings_path: str) -> bool:
    """True iff the project's `.claude/settings.json` already references the
    agency plugin (so install can offer the one-liner fix only when needed)."""
    try:
        with open(settings_path, encoding="utf-8") as f:
            return "agency" in f.read()
    except OSError:
        return False


_AGENCY_README = """# .agency/ — central graph DB

The agency engine's bi-temporal provenance graph lives here as
`session.db`. Per Spec 020 the DB is **committed to git** so team
learnings + observation reflections persist across clones and
branch checkouts.

## Inspect

```bash
sqlite3 .agency/session.db
.tables
SELECT * FROM nodes LIMIT 5;
```

## Reset

```bash
rm .agency/session.db
python -m agency.install     # regenerates an empty DB on next engine start
```

## Backup

```bash
sqlite3 .agency/session.db ".backup .agency/backup-$(date +%F).db"
```

## Merge conflicts

The DB is binary; git can't auto-merge. Recovery: each branch can
export to JSON via `dogfood.export` (Spec 020 deliverable), then both
exports replay against a fresh DB on the merged commit.

See `Plan/020-central-graph-db/spec.md` for the full design.
"""

_GITATTRS_MARKER = "# Spec 020 — central graph DB"
_GITATTRS_BLOCK = (
    f"{_GITATTRS_MARKER}\n"
    ".agency/session.db binary\n"
    ".agency/session.db diff=sqlite\n"
)


def scaffold_agency_dir(root: str) -> list[str]:
    """Create ``<root>/.agency/`` + ``.gitkeep`` + ``README.md`` (Spec 020).
    Idempotent — re-running on a populated dir is a no-op. Returns the list
    of paths that were CREATED on this call (empty if all already present)."""
    agency_dir = os.path.join(root, ".agency")
    os.makedirs(agency_dir, exist_ok=True)
    written: list[str] = []
    gitkeep = os.path.join(agency_dir, ".gitkeep")
    if not os.path.exists(gitkeep):
        with open(gitkeep, "w") as f:
            pass
        written.append(gitkeep)
    readme = os.path.join(agency_dir, "README.md")
    if not os.path.exists(readme):
        with open(readme, "w") as f:
            f.write(_AGENCY_README)
        written.append(readme)
    # Spec 021 — keep ONLY the ephemeral monitor SLOG out of git. NOTE:
    # session.db is deliberately NOT ignored — Spec 020 commits the graph (see
    # _AGENCY_README + the .gitattributes binary marker); ignoring it here would
    # hide the shared provenance graph after the first engine run.
    gitignore = os.path.join(agency_dir, ".gitignore")
    if not os.path.exists(gitignore):
        with open(gitignore, "w") as f:
            f.write("# Spec 021 — ephemeral monitor SLOG (NOT graph state).\n"
                    "# session.db is committed (Spec 020) — do not add it here.\n"
                    "monitor.log\n"
                    "monitor.log.*\n")
        written.append(gitignore)
    return written


def update_gitattributes(root: str) -> bool:
    """Append the Spec 020 binary-marker block to ``<root>/.gitattributes``
    if not already present. Returns True iff the file was modified."""
    path = os.path.join(root, ".gitattributes")
    existing = ""
    if os.path.exists(path):
        with open(path) as f:
            existing = f.read()
    if _GITATTRS_MARKER in existing:
        return False
    with open(path, "a") as f:
        if existing and not existing.endswith("\n"):
            f.write("\n")
        if existing:
            f.write("\n")
        f.write(_GITATTRS_BLOCK)
    return True


def scaffold_db(root: str) -> dict:
    """Run both Spec 020 scaffolds. Returns {written, gitattributes_updated}."""
    return {
        "written": scaffold_agency_dir(root),
        "gitattributes_updated": update_gitattributes(root),
    }


# ---- Spec 029 §A — CLAUDE.md onboarding snippet ----------------------------

_CLAUDE_MD_MARKER_START = "<!-- agency:onboarding:start -->"
_CLAUDE_MD_MARKER_END = "<!-- agency:onboarding:end -->"

_CLAUDE_MD_SNIPPET = f"""\
{_CLAUDE_MD_MARKER_START}
## Agency plugin — onboarding (auto-generated, do not edit between markers)

This repo carries an `.agency/session.db` provenance graph (Spec 020 —
committed to git so team learnings travel with the repo).

### Wire contract — 3 tools (CORE.md)

The agency MCP server exposes ONE lean contract:

| tool | purpose |
|---|---|
| `search` | discover capabilities + verbs by keyword |
| `get_schema` | fetch parameter schemas for a found verb |
| `execute` | run a Python block; chain `await call_tool(...)` calls inside |

Plus four engine-substrate onboarding tools:

- `agency_welcome` — one-shot first call; returns the wire contract +
  a chained code-mode example + the live capability tier + the discipline-
  skills roster + the resolved DB path. **Start here.** No intent_id.
- `agency_install` — scaffold `.agency/` + refresh this snippet. Idempotent.
- `agency_doctor` — health check (Spec 030): python version, deps, DB
  reachability, env-var presence. Call when something silently fails.
- `intent_bootstrap` — mint AND confirm the Intent every verb SERVES
  against. The only tool that does NOT require an existing `intent_id`.

### Code-mode chaining — one block, one return

`execute` runs ONE Python block in a sandbox; every `await call_tool(...)`
inside crosses NO extra wire hops; ONE value crosses back. Chain instead
of per-call — it's the headline win of the substrate.

**Sandbox constraints (Spec 282 G — know them before batching):**
- **≤ 50 `call_tool` per `execute` block** — batch at ≤ 45; split larger
  work across blocks or use the CLI lane (`python -m agency.cli execute`).
- **No file I/O** — the sandbox has no `open()`; persist via capability
  verbs, never the filesystem. `try/except`, `import json`, loops are fine.
- A failed `call_tool` aborts the REST of the block, but writes already
  made **persist** (not rolled back) — make batch scripts idempotent.

```python
await call_tool('execute', {{'code': '''
    # 1. mint the intent every cap verb will SERVE
    iid = (await call_tool("intent_bootstrap", {{
        "purpose": "<why>", "deliverable": "<what>", "acceptance": "<verify>",
    }}))["intent_id"]
    # 2. chain N verb calls — only the final return crosses the wire
    r = await call_tool("capability_<cap>_<verb>", {{
        "intent_id": iid, "agent_id": "agent:me",
    }})
    # 3. record the lesson so the graph carries it (provenance moat)
    await call_tool("capability_reflect_note", {{
        "intent_id": iid, "agent_id": "agent:me",
        "scope": "observation", "text": "<lesson>",
    }})
    return r
'''}})
```

### Session mode — walk discipline skills, don't improvise

Every walkable skill IS a Lifecycle template (Spec 114). Walk them via
`develop.skill_walk` so the engine bounds context one phase at a time:

- `develop.brainstorm` — explore intent before code
- `develop.write_spec` — harden a draft into a spec
- `develop.implement` — RED → GREEN → commit → push (TDD walker)
- `develop.skill_walk` — walk any cap's walkable skill
- `develop.session_init` — open + resume a session

### Provenance is the moat — verb-first beats raw tools

Capability verbs auto-record Invocations + SERVES edges + Artefacts.
Raw `Bash`/`Edit` actions don't. Prefer:

| action | verb | raw fallback |
|---|---|---|
| run tests | `develop.test` | Bash `pytest` |
| commit | `branch.commit_smart` | Bash `git commit` |
| push + open PR | `branch.finish_branch` | Bash + `gh` |
| dispatch subagent | `subagent.dispatch` | Agent tool |
| search code | `search` + `analyze.*` | Grep / Glob |
| critical thinking | `intent.<method>` (8 methods, Spec 091) | chat |

When in doubt, call `agency_welcome` first — sub-1KB, pure introspection,
state-aware (fresh-graph → bootstrap; populated → discovery + provenance).

### Rule 0 — never assume; ask

Whenever a decision would otherwise rest on an **assumption** — a domain
fact, an enum value, which source wins on conflict, scope, a name, or any
ambiguous requirement — **STOP and ask the user** with the `AskUserQuestion`
tool instead of guessing. A wrong assumption baked into work is expensive to
unwind; a question is cheap. This is a hard rule, not a soft preference.

The engine reinforces it so the discipline survives a forgetful session:

- **Hard skill-gates pause for explicit sign-off.** A `develop.skill_walk`
  phase marked `gate: hard` returns `input-required` and blocks until you
  confirm — resume with `resume_from=<PHASE>`. Do not self-approve; surface
  the gate to the user.
- **Verbs fail LOUD, never invent.** A verb that cannot resolve a required
  value returns a PERMANENT typed error (Spec 282) listing the legal options
  rather than picking one. Read the error; ask if the choice is the user's.
- **Discover, don't guess, the surface.** `search` / `get_schema` return the
  real verbs + their enum members (Spec 284 surfaces closed-enum values up
  front) — consult them before assuming a parameter or value exists.
{_CLAUDE_MD_MARKER_END}
"""


def write_claude_md_snippet(root: str) -> tuple[str, bool]:
    """Write or refresh the onboarding snippet in <root>/CLAUDE.md.

    Returns (path, updated). ``updated`` is True iff the file content
    actually changed. Existing CLAUDE.md content OUTSIDE the markers is
    never touched; the block between markers is REPLACED on every run
    (so a re-install picks up updated guidance). If no CLAUDE.md exists,
    one is created with just the snippet."""
    path = os.path.join(root, "CLAUDE.md")
    if not os.path.exists(path):
        with open(path, "w") as f:
            f.write(_CLAUDE_MD_SNIPPET)
        return path, True
    with open(path) as f:
        existing = f.read()
    if _CLAUDE_MD_MARKER_START in existing and _CLAUDE_MD_MARKER_END in existing:
        start = existing.index(_CLAUDE_MD_MARKER_START)
        end = existing.index(_CLAUDE_MD_MARKER_END) + len(_CLAUDE_MD_MARKER_END)
        # _CLAUDE_MD_SNIPPET ends with "\n"; preserve a single trailing newline
        # at the spot the markers occupied so adjacent user content lines up.
        new = existing[:start] + _CLAUDE_MD_SNIPPET.rstrip("\n") + existing[end:]
    else:
        sep = "" if existing.endswith("\n") else "\n"
        new = existing + sep + "\n" + _CLAUDE_MD_SNIPPET
    if new == existing:
        return path, False
    with open(path, "w") as f:
        f.write(new)
    return path, True


def install_op(target: str | None = None) -> dict:
    """The Spec 029 MCP-callable install operation.

    Resolves the target (arg → CLAUDE_PROJECT_DIR → cwd), runs
    ``scaffold_db`` (idempotent), writes the CLAUDE.md onboarding
    snippet, and returns a structured summary that names the literal
    paths for verification. Reuses ``_scaffold_target`` so the logic
    matches the existing bash entry point."""
    root = target or _scaffold_target(os.getcwd())
    os.makedirs(root, exist_ok=True)
    scaffold = scaffold_db(root)
    claude_md_path, claude_md_updated = write_claude_md_snippet(root)
    return {
        "target": root,
        "scaffolded": [str(p) for p in scaffold["written"]],
        "gitattributes_updated": scaffold["gitattributes_updated"],
        "claude_md_path": claude_md_path,
        "claude_md_updated": claude_md_updated,
        "next": (
            "call_tool('intent_bootstrap', {'purpose': '...', "
            "'deliverable': '...', 'acceptance': '...'})"
        ),
    }


def _scaffold_target(install_root: str) -> str:
    """Where the Spec 020 ``.agency/`` provenance scaffold must land.

    Plugin root vs project root — two different directories:
    - ``install_root`` (the positional ``root`` arg, = ``${CLAUDE_PLUGIN_ROOT}``
      under a marketplace install) holds the read-only plugin CODE: the
      manifest, ``.mcp.json``, the help skill. Those are written there by
      ``write()``.
    - The graph DB, however, resolves to ``${CLAUDE_PROJECT_DIR}/.agency/
      session.db`` (see ``_mcp_config`` + ``_db_path.resolve_db_path``). The
      ``.agency/`` scaffold (README/.gitkeep/.gitattributes) must therefore
      sit in the user's PROJECT, not the plugin install dir — otherwise a
      marketplace-installed plugin scaffolds the provenance home next to the
      code where no DB ever lives, and the project never gets its committed
      ``.agency/`` files.

    So: prefer ``${CLAUDE_PROJECT_DIR}`` when set (the plugin-runtime case),
    falling back to ``install_root`` (the local-dev case, where the plugin
    root IS the project root)."""
    return os.environ.get("CLAUDE_PROJECT_DIR") or install_root


if __name__ == "__main__":
    sys.exit(main())
