"""Setup for the Agency Plugin for Claude Code.

This is the "in setup" that maps the harness-in-harness MICRO-skills (the engine's
capability verbs) into MACRO-skills (the capabilities themselves) behind a single
`help` discovery surface. It is SELF-HOSTED: the manifest, the MCP-server
declaration, the marketplace catalogue, the `help` skill, and the `/agency:help`
command are all generated by DOGFOODING the plugin-development capability
(`plugin.scaffold` / `author_skill` / `author_command`) over the live registry —
the engine authors its own Claude Code plugin.

Usage::

    python -m agency.install                       # regen manifest etc into the
                                                   # current install root
    python -m agency.install --scaffold-db         # also create .agency/ + the
                                                   # .gitattributes binary marker
                                                   # (Spec 020); idempotent
    python -m agency.install <root>                # write under <root> instead
                                                   # of the package's repo root

The bash wrapper ``bin/agency-install`` calls ``python -m agency.install
--scaffold-db`` on fresh installs so the Spec 020 ``.agency/`` directory
lands in $1 (= CLAUDE_PLUGIN_ROOT under marketplace install; the local
project root during dev).
"""
from __future__ import annotations

import argparse
import json
import os
import sys

from .capabilities.plugin import author_command, author_skill, help_map
from .engine import Engine
from . import templates

NAME = "agency"
VERSION = "0.1.0"
DESCRIPTION = ("Harness-in-harness agency engine: code-mode capabilities "
               "(macroskills) over one provenance graph.")
DISPLAY_NAME = "Agency"
AUTHOR = "netzkontrast"
HOMEPAGE = "https://github.com/netzkontrast/agency"
REPOSITORY = "https://github.com/netzkontrast/agency"
LICENSE = "MIT"

HELP_DESC = ("Use when you need to discover the agency engine's capabilities "
             "(macroskills) and their verbs (the micro-skills).")
CMD_DESC = "Use when you want to list the agency capabilities and their verbs."

# The MCP server this plugin installs surfaces three tools to Claude Code:
# `mcp__plugin_agency_agency__{search,get_schema,execute}`. When the skill
# is read inside Claude Code those are reachable in-process and should be
# the primary surface. The bash bootstrap remains for Jules / no-MCP
# harnesses (see AGENCY_PROTOCOL.md) — the engine is isomorphic over both.
HELP_ALLOWED_TOOLS = (
    "  - mcp__plugin_agency_agency__search\n"
    "  - mcp__plugin_agency_agency__get_schema\n"
    "  - mcp__plugin_agency_agency__execute\n"
    "  - Bash"
)

_MCP_QUICKSTART = (
    "## Quick start — MCP (Claude Code)\n\n"
    "The plugin installs an MCP server exposing three tools:\n"
    "`mcp__plugin_agency_agency__search`, `…__get_schema`, `…__execute`.\n"
    "Inside `execute`, chain capability calls via `call_tool(...)` — only\n"
    "the return crosses back into your context.\n\n"
    "```python\n"
    "# 1. Discover a verb (token-cheap)\n"
    'await mcp__plugin_agency_agency__search(query="reflect note", limit=3)\n\n'
    "# 2. Run it (sandboxed; intermediate results stay in-sandbox)\n"
    "await mcp__plugin_agency_agency__execute(code=\"\"\"\n"
    "  r = await call_tool('capability_plugin_help', {'intent_id': iid})\n"
    "  return r\n"
    "\"\"\")\n"
    "```\n\n"
    "`intent_id` must be a captured Intent — today only the bash CLI exposes\n"
    "`intent` (see fallback below). Tracking issue: add a `capability_intent_capture`\n"
    "verb so MCP-only sessions can self-bootstrap.\n\n"
    "## Quick start — bash (Jules / no-MCP)\n\n"
    "```bash\n"
    'AGENCY="${CLAUDE_PLUGIN_ROOT}/bin/agency"\n'
    'iid=$("$AGENCY" --db agency.db intent --purpose help --deliverable map --acceptance ok \\\n'
    '      | python3 -c \'import sys,json; print(json.load(sys.stdin)["intent_id"])\')\n'
    '"$AGENCY" --db agency.db execute --code \\\n'
    "  \"return await call_tool('capability_plugin_help', {'intent_id': '$iid'})\"\n"
    "```\n\n"
)

CMD_BODY = (
    _MCP_QUICKSTART
    + "Use the plugin's `bin/agency` wrapper — it resolves the plugin venv\n"
    "+ PYTHONPATH so the `agency` package is always importable. Bootstrap\n"
    "an intent, then call the help verb with its id:\n\n"
    "    AGENCY=\"${CLAUDE_PLUGIN_ROOT}/bin/agency\"\n"
    "    iid=$(\"$AGENCY\" --db agency.db intent --purpose help "
    "--deliverable map --acceptance ok | python3 -c "
    "'import sys,json; print(json.load(sys.stdin)[\"intent_id\"])')\n"
    "    \"$AGENCY\" --db agency.db execute --code "
    "\"return await call_tool('capability_plugin_help', {'intent_id': '$iid'})\"\n"
)


def _manifest() -> dict:
    """The enriched `.claude-plugin/plugin.json` for Claude Code. Built on top of
    `templates.manifest_obj` (the dogfooded base shape) with the install-time
    fields a marketplace listing wants and a `userConfig` for `JULES_API_KEY`
    that the MCP server reads via `${user_config.jules_api_key}`."""
    m = templates.manifest_obj(NAME, VERSION, DESCRIPTION)
    m["displayName"] = DISPLAY_NAME
    m["author"] = {"name": AUTHOR}
    m["homepage"] = HOMEPAGE
    m["repository"] = REPOSITORY
    m["license"] = LICENSE
    m["userConfig"] = {
        "jules_api_key": {
            "type": "string",
            "title": "Jules API Key",
            "description": ("Optional. Needed only for the `jules` capability "
                            "(remote async coding agent). Get a key from "
                            "https://jules.google.com — Claude Code stores it "
                            "in your system keychain and exposes it to the "
                            "Agency MCP server as JULES_API_KEY."),
            "sensitive": True,
        }
    }
    return m


def _mcp_config() -> dict:
    """`.mcp.json` — the in-plugin MCP server declaration. Launches the Agency
    FastMCP engine in stdio mode via the bin/ wrapper, which picks the plugin's
    venv if present and falls back to the system Python.

    Path conventions:
    - ``${CLAUDE_PLUGIN_ROOT}`` — the plugin install dir (read-only code).
      Holds the launcher + PYTHONPATH; survives plugin updates by design.
    - ``${CLAUDE_PROJECT_DIR}`` — the user's project root. Holds the graph
      DB so MCP + bash CLI converge on one store per project (the CLI
      defaults to ``./.agency/session.db`` via ``_db_path.resolve_db_path``;
      pointing AGENCY_DB at the same path is the unification — see
      reflection:9cd97a38 + tests/test_install_db_path.py).
    - ``${user_config.jules_api_key}`` — wired by the manifest's
      ``userConfig`` (secret).

    Previously this used ``${CLAUDE_PLUGIN_DATA}/agency.db`` (a path
    outside the project), which diverged from the CLI default and
    silently split observations between two stores. The plugin-data
    path is the right home for cross-project plugin state; the agency
    graph is per-project (the moat IS the graph; the graph lives with
    the project the agency is working on)."""
    return {
        "mcpServers": {
            "agency": {
                "command": "${CLAUDE_PLUGIN_ROOT}/bin/agency-mcp",
                "args": [],
                "env": {
                    "PYTHONPATH": "${CLAUDE_PLUGIN_ROOT}",
                    "AGENCY_DB": "${CLAUDE_PROJECT_DIR}/.agency/session.db",
                    "JULES_API_KEY": "${user_config.jules_api_key}",
                },
            }
        }
    }


def _marketplace() -> dict:
    """`.claude-plugin/marketplace.json` — single-plugin marketplace catalogue
    (this repo IS its own marketplace). `source: "./"` means the plugin source
    IS the marketplace root, so `/plugin marketplace add netzkontrast/agency`
    + `/plugin install agency@agency` installs from this repo directly."""
    return {
        "name": NAME,
        "owner": {"name": AUTHOR},
        "plugins": [
            {
                "name": NAME,
                "source": "./",
                "version": VERSION,
                "description": DESCRIPTION,
                "homepage": HOMEPAGE,
                "license": LICENSE,
            }
        ],
    }


def generate(engine: Engine) -> dict[str, str]:
    """Produce the install files from the LIVE registry (so `help` always reflects
    the real capability set). Returns {relative_path: file_contents}.

    The `help` skill body is `_MCP_QUICKSTART` (MCP-first, bash-fallback)
    PREPENDED to the auto-discovered capability map from `plugin.help_map`.
    Two surfaces in one skill so MCP-equipped (Claude Code) and bash-only
    (Jules) harnesses both find their idiomatic call shape — the canon's
    isomorphism guarantee landing in the install artefacts."""
    reg = engine.registry
    caps = {n: list(reg.get(n).verbs) for n in reg.names()}
    help_doc = help_map(caps)["result"]["doc"]
    skill_body = _MCP_QUICKSTART + "\n" + help_doc
    return {
        ".claude-plugin/plugin.json":      json.dumps(_manifest(), indent=2),
        ".claude-plugin/marketplace.json": json.dumps(_marketplace(), indent=2),
        ".mcp.json":                       json.dumps(_mcp_config(), indent=2),
        "skills/help/SKILL.md":            author_skill(
            "help", HELP_DESC, skill_body,
            allowed_tools=HELP_ALLOWED_TOOLS,
        )["result"],
        "commands/help.md":                author_command("help", CMD_DESC, CMD_BODY)["result"],
    }


def write(root: str) -> list[str]:
    engine = Engine(":memory:")
    try:
        files = generate(engine)
    finally:
        engine.memory.close()
    written = []
    for rel, content in files.items():
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(content)
        written.append(path)
    return written


_AGENCY_README = """# .agency/ — central graph DB

The agency engine's bi-temporal provenance graph lives here as
`session.db`. Per Spec 020 the DB is **committed to git** so team
learnings + observation reflections persist across clones and
branch checkouts.

## Inspect

```bash
sqlite3 .agency/session.db
.tables
SELECT * FROM nodes LIMIT 5;
```

## Reset

```bash
rm .agency/session.db
python -m agency.install     # regenerates an empty DB on next engine start
```

## Backup

```bash
sqlite3 .agency/session.db ".backup .agency/backup-$(date +%F).db"
```

## Merge conflicts

The DB is binary; git can't auto-merge. Recovery: each branch can
export to JSON via `dogfood.export` (Spec 020 deliverable), then both
exports replay against a fresh DB on the merged commit.

See `Plan/020-central-graph-db/spec.md` for the full design.
"""

_GITATTRS_MARKER = "# Spec 020 — central graph DB"
_GITATTRS_BLOCK = (
    f"{_GITATTRS_MARKER}\n"
    ".agency/session.db binary\n"
    ".agency/session.db diff=sqlite\n"
)


def scaffold_agency_dir(root: str) -> list[str]:
    """Create ``<root>/.agency/`` + ``.gitkeep`` + ``README.md`` (Spec 020).
    Idempotent — re-running on a populated dir is a no-op. Returns the list
    of paths that were CREATED on this call (empty if all already present)."""
    agency_dir = os.path.join(root, ".agency")
    os.makedirs(agency_dir, exist_ok=True)
    written: list[str] = []
    gitkeep = os.path.join(agency_dir, ".gitkeep")
    if not os.path.exists(gitkeep):
        with open(gitkeep, "w") as f:
            pass
        written.append(gitkeep)
    readme = os.path.join(agency_dir, "README.md")
    if not os.path.exists(readme):
        with open(readme, "w") as f:
            f.write(_AGENCY_README)
        written.append(readme)
    return written


def update_gitattributes(root: str) -> bool:
    """Append the Spec 020 binary-marker block to ``<root>/.gitattributes``
    if not already present. Returns True iff the file was modified."""
    path = os.path.join(root, ".gitattributes")
    existing = ""
    if os.path.exists(path):
        with open(path) as f:
            existing = f.read()
    if _GITATTRS_MARKER in existing:
        return False
    with open(path, "a") as f:
        if existing and not existing.endswith("\n"):
            f.write("\n")
        if existing:
            f.write("\n")
        f.write(_GITATTRS_BLOCK)
    return True


def scaffold_db(root: str) -> dict:
    """Run both Spec 020 scaffolds. Returns {written, gitattributes_updated}."""
    return {
        "written": scaffold_agency_dir(root),
        "gitattributes_updated": update_gitattributes(root),
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog="python -m agency.install",
                                     description="Regenerate the Claude Code plugin install files.")
    parser.add_argument("root", nargs="?", default=None,
                        help="install root (default: this repo's root)")
    parser.add_argument("--scaffold-db", action="store_true",
                        help="also create .agency/ + .gitattributes binary marker (Spec 020)")
    ns = parser.parse_args()
    target = ns.root or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for p in write(target):
        print(p)
    if ns.scaffold_db:
        result = scaffold_db(target)
        for p in result["written"]:
            print(p)
        if result["gitattributes_updated"]:
            print(os.path.join(target, ".gitattributes"))
